import { useState } from 'react';
import { activeVisit, replaceVisit } from '../../ceremony';
import { allLots, availableIndexObjectives, categoryTitle, catalogue, getItem, redeemObjectiveInState } from '../../market';
import type { Lot, MarketState, Visit } from '../../types';
import { errorText } from '../../ui/ErrorDialog';
import { campaignFetch } from '../../runtime';

const price = (lot: Lot) => { const value = getItem(lot.itemId)!.price; return `${value.tc} TC${value.rp ? ` + ${value.rp} RP` : ''}${value.auction ? ' minimum bid' : ''}`; };
const poolLabel = (pool: string) => pool === 'unit3' ? 'Unit 3TC' : pool === 'unit4' ? 'Unit 4TC' : pool.replace(/-/g, ' ').replace(/\b\w/g, value => value.toUpperCase());
const poolRevealArt: Record<Lot['pool'], string> = { field: '/hybrid-campaign/assets/pool-reveals/field-asset-auction-pedestal.png', standard: '/hybrid-campaign/assets/pool-reveals/standard-item-auction-pedestal.png', ordinary: '/hybrid-campaign/assets/pool-reveals/ordinary-item-auction-pedestal.png', powerful: '/hybrid-campaign/assets/pool-reveals/powerful-item-auction-pedestal.png', exceptional: '/hybrid-campaign/assets/pool-reveals/exceptional-item-auction-pedestal.png', unit3: '/hybrid-campaign/assets/pool-reveals/unit-3-trade-coin-auction-pedestal.png', unit4: '/hybrid-campaign/assets/pool-reveals/unit-4-trade-coin-auction-pedestal.png', 'marquee-unit': '/hybrid-campaign/assets/pool-reveals/marquee-unit-auction-pedestal.png', 'marquee-relic': '/hybrid-campaign/assets/pool-reveals/marquee-relic-auction-pedestal.png' };
const revealSummary = (item: ReturnType<typeof getItem>) => item?.rules.split(/(?<=[.!?])\s+/)[0] ?? '';
const fail = (report: (message: string) => void, error: unknown) => { const text = errorText(error); report(text); dispatchEvent(new CustomEvent('gilded-index-error', { detail: text })); };

function CeremonyPresentation({ visit, state }: { visit: Visit; state: MarketState }) {
  const timeline = state.ceremony;
  const lot = timeline.lotPosition ? allLots(visit).find(entry => entry.position === timeline.lotPosition) : undefined;
  if (timeline.cue === 'cassian-opening') return <section className="cassian-opening"><div className="cassian-figure"><img src="/hybrid-campaign/assets/ceremony/cassian-verid-opening-portrait.png" alt="Cassian Verid"/></div><div className="cassian-address"><p className="eyebrow">Cassian Verid opens the private register</p><h1>The Gilded Index</h1><p>By sealed warrant and cold trust, Cassian Verid yields the floor to Miren Quill.</p><span>THE FIRST FACTOR TAKES THE ROSTRUM</span></div></section>;
  if (timeline.cue === 'security-interruption' || timeline.status === 'awaiting-chaos-resolution') return <section className="miren-reveal miren-interrupted"><div className="miren-stage"><p className="interruption-signal">SECURITY CORDON · REGISTER HELD</p><div className="guard-interruption"><img src="/hybrid-campaign/assets/ceremony/garran-thule-miren-evacuation.png" alt="Garran Thule extracting Miren Quill"/></div><p className="miren-voice">The Index has been interrupted. Cassian’s private control will record the outcome before the register reopens.</p></div></section>;
  if (!lot) return null;
  const item = getItem(lot.itemId)!; const revealing = timeline.cue === 'reveal';
  return <section className={revealing ? 'miren-reveal is-revealed' : 'miren-reveal is-addressing'}><div className="miren-stage"><p className="eyebrow">Miren Quill · lot {lot.position} of {visit.lots.length}</p><div className="miren-figure"><i className="vox-rings"/><img src="/hybrid-campaign/assets/ceremony/miren-quill-rostrum-portrait.png" alt="Miren Quill at the rostrum"/></div><p className="miren-voice">{item.mirenAnnouncement}</p></div>{revealing && <article className="reveal-card"><img src={poolRevealArt[lot.pool]} alt={`${categoryTitle(lot.pool)} auction display`}/><div><p className="eyebrow">Lot {lot.position} · {categoryTitle(lot.pool)}</p><h1>{item.name}</h1><p>{item.origin} · {price(lot)}</p><p>{item.description}</p><section><h2>Certified effect</h2><p>{revealSummary(item)}</p></section></div></article>}</section>;
}

function Opportunity({ visit }: { visit: Visit }) { const list = (visit.objectiveRecords ?? []).filter(entry => entry.state === 'presented' || entry.state === 'redeemed'); return list.length ? <section className="opportunity"><h2>Opportunity Register</h2>{list.map(objective => <article key={objective.id}><h3>{objective.title}</h3><p>{objective.summary}</p>{objective.offers.filter(offer => offer.enabled !== false).map(offer => <p key={offer.id}><strong>{offer.recipientName}:</strong> {offer.playerText} {offer.amount ? `(${offer.amount} ${offer.rewardType.toUpperCase()})` : offer.detail}</p>)}</article>)}</section> : null; }

export function Display({ state, online }: { state: MarketState; online: boolean }) {
  const visit = activeVisit(state); const show = !!visit && (state.ceremony.status === 'catalogue' || visit.phase === 'resolved'); const presenting = !!visit && ['running', 'paused', 'awaiting-chaos-resolution'].includes(state.ceremony.status); const marquee = visit && allLots(visit).find(entry => entry.pool.startsWith('marquee')); const check = marquee && (visit?.auctionChecks ?? []).filter(entry => entry.lotId === marquee.id).at(-1);
  return <main className="display"><div className="archive-backdrop"/><header className="display-header"><img className="crest" src="/hybrid-campaign/assets/branding/gilded-index-crest-emblem.png" alt="The Gilded Index crest"/><div><p>The Gilded Index</p><span>MIREN QUILL · FIRST FACTOR'S PRIVATE REGISTER</span></div><span className={online ? 'uplink online' : 'uplink offline'}>{online ? 'LIVE' : 'RECONNECTING'}</span></header>{presenting ? <CeremonyPresentation visit={visit!} state={state}/> : !show ? <section className="display-idle"><p className="eyebrow">Miren's register awaits consent</p><h1>THE GILDED INDEX</h1></section> : <section className="final-board">{check && <aside className="player-auction"><h2>Current marquee bidding</h2><p>The Cell has tabled {check.playerTc} TC + {check.playerRp} RP.</p><p>{check.npcTc ? `${check.responder} has answered at ${check.npcTc} TC.` : 'No counterbid has been recorded.'}</p></aside>}<div className="catalogue-grid">{allLots(visit!).map(lot => { const outcome = lot.status === 'purchased' ? 'Claimed by the Cell' : lot.status === 'npc-won' ? 'Sold' : lot.status === 'unsold' ? 'Withdrawn' : ''; return <article key={lot.id} className="catalogue-card"><span>LOT {lot.position} · {categoryTitle(lot.pool)}</span><h2>{getItem(lot.itemId)!.name}</h2><p>{getItem(lot.itemId)!.origin}</p><strong>{price(lot)}</strong>{outcome && <i className="outcome">{outcome}</i>}</article>; })}</div><Opportunity visit={visit!}/></section>}</main>;
}

export function Inventory({ state }: { state: MarketState }) { const [search, setSearch] = useState(''); const [pool, setPool] = useState(''); const [stateFilter, setStateFilter] = useState(''); const active = activeVisit(state); const current = new Set(active ? allLots(active).map(lot => lot.itemId) : []); const rows = catalogue.filter(item => (!search || `${item.name} ${item.origin}`.toLowerCase().includes(search.toLowerCase())) && (!pool || item.pool === pool) && (!stateFilter || (stateFilter === 'active' ? current.has(item.id) : stateFilter === 'retired' ? state.retired.includes(item.id) : stateFilter === 'cooldown' ? !!state.cooldowns[item.id] : !state.retired.includes(item.id) && !state.cooldowns[item.id]))); return <main className="control inventory"><header><p className="eyebrow">GM-only canonical stock register</p><h1>Gilded Index Inventory</h1><a className="display-link" href="#/">Return to Control</a></header><div className="filters"><input placeholder="Search stock or origin" value={search} onChange={event => setSearch(event.target.value)}/><select value={pool} onChange={event => setPool(event.target.value)}><option value="">All Pools</option>{[...new Set(catalogue.map(item => item.pool))].map(entry => <option key={entry} value={entry}>{poolLabel(entry)}</option>)}</select><select value={stateFilter} onChange={event => setStateFilter(event.target.value)}><option value="">All States</option><option value="available">Available</option><option value="cooldown">Cooldown</option><option value="retired">Retired</option><option value="active">In Active Visit</option></select></div>{rows.map(item => <article className="inventory-row" key={item.id}><strong>{item.name}</strong><span>{poolLabel(item.pool)} · {item.price.tc} TC + {item.price.rp} RP · {item.origin}</span><span>{state.retired.includes(item.id) ? 'Retired' : state.cooldowns[item.id] ? `Cooldown: ${state.cooldowns[item.id]} visit(s)` : 'Available'}{current.has(item.id) ? ' · Active Lot' : ''}</span></article>)}</main>; }

export function Exchange({ state, commit, report }: { state: MarketState; commit: (state: MarketState) => Promise<void>; report: (text: string) => void }) { const visit = activeVisit(state); const objectives = visit ? availableIndexObjectives(visit) : []; const legacyRequests = (visit?.tradeRequests ?? []).filter(request => request.kind === 'objective'); const tender = () => { if (!visit) return; const idempotencyKey = globalThis.crypto?.randomUUID?.() ?? `rp-tender-${Date.now()}`; void campaignFetch('/campaign/economy/convert-rp', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ visitId: visit.id, idempotencyKey }) }).then(async response => { const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error ?? 'Miren could not tender the shared RP.'); location.reload(); }).catch(error => fail(report, error)); }; const redeem = (objectiveId: string, offerId: string) => void commit(redeemObjectiveInState(state, visit!.id, objectiveId, offerId)).catch(error => fail(report, error)); return <main className="display exchange"><div className="archive-backdrop"/><header className="display-header"><img className="crest" src="/hybrid-campaign/assets/branding/gilded-index-crest-emblem.png" alt="The Gilded Index crest"/><div><p>The Gilded Index</p><span>MIREN QUILL · RECOVERY COUNTER</span></div></header><section className="exchange-counter"><div className="counter-host"><img src="/hybrid-campaign/assets/exchange/miren-quill-counter-portrait.png" alt="Miren Quill at the recovery counter"/><p>“The trust is ready to receive what you have recovered.”</p></div><div className="counter-ledger"><p className="eyebrow">Miren Quill's counter</p><h1>Recovery exchange</h1><p>Coin held in present trust: <strong>{visit?.tradeCoin?.balance ?? 0} TC</strong></p><button className="index-button" disabled={!visit} onClick={tender}>Tender {state.exchangeRpPerTc} RP for 1 TC</button><section className="counter-objective"><h2>Available Index Objectives</h2>{objectives.length ? <div className="objective-credit-list">{objectives.map(({ objective, offer }) => <article key={objective.id}><div><strong>{objective.title}</strong><span>{offer.amount} TC · {offer.playerText}</span></div><button className="index-button" onClick={() => redeem(objective.id, offer.id)}>Redeem for {offer.amount} TC</button></article>)}</div> : <p className="counter-empty">No presented Gilded Index objectives are available for Trade Coin.</p>}</section>{legacyRequests.length > 0 && <section className="counter-objective objective-history"><h2>Earlier objective credits</h2>{legacyRequests.map(request => <p key={request.id}><strong>{request.amount} TC · {request.status}</strong> {request.label}</p>)}</section>}</div></section></main>; }
