import type { IncomingMessage, ServerResponse } from 'node:http';
import type { Plugin } from 'vite';
import { CampaignService, type ActorContext, type TrustedRole } from './campaign-service';
import type { AuthorityMandate, AuthorityResult, CampaignDate, CampaignDebt, CampaignDocketActivity, CampaignHook, CampaignIdentity, CampaignOperation, CampaignPublication, CampaignRequisition, CampaignSession, Cipher17State, ClaimedAsset, ClaimedAssetDisposition, CollectionProposal, CorruptionWebEdge, DiscoveryInstance, EvidenceRecord, ForceProfile, ForceUnit, MissionTruthSheet, NpcRelationship, OperationDeployment, OperationResult, ProgressionRequest, PublicationAcknowledgement, RosterDraft, RosetteInvocation, RpTransactionKind, RulesSourcePackage, UnitAttachment } from '../src/types';

const readBody = (request: IncomingMessage) => new Promise<unknown>((resolveBody, reject) => { let body = ''; let size = 0; request.on('data', (chunk: Buffer) => { size += chunk.length; if (size > 7 * 1024 * 1024) { reject(new Error('Request body exceeds the 7 MB safe API limit.')); request.destroy(); return; } body += chunk; }); request.on('end', () => { try { resolveBody(body ? JSON.parse(body) : {}); } catch (error) { reject(error); } }); request.on('error', reject); });
export const trustedLocalActorFrom = (request: IncomingMessage): ActorContext => ({ role: (request.headers['x-trusted-local-role'] ?? 'owner-gm') as TrustedRole, identityId: typeof request.headers['x-campaign-identity'] === 'string' ? request.headers['x-campaign-identity'] : undefined });
export type ApiActorResolver = (request: IncomingMessage) => Promise<ActorContext> | ActorContext;
const json = (response: ServerResponse, value: unknown, status = 200) => { response.statusCode = status; response.setHeader('Content-Type', 'application/json'); response.end(JSON.stringify(value)); };
const error = (response: ServerResponse, value: unknown) => json(response, { error: value instanceof Error ? value.message : 'The campaign service rejected this request.' }, 400);

/** Shared API handler. Vite supplies the trusted-local resolver; production supplies a session resolver. */
export function campaignApiHandler(service: CampaignService, persist?: () => Promise<void>, actorResolver: ApiActorResolver = trustedLocalActorFrom, basePath = '') {
  return async (request: IncomingMessage, response: ServerResponse) => {
      try {
        const actor = await actorResolver(request); const url = new URL(request.url ?? '/', 'http://localhost'); const rawPath = url.pathname;
        const path = basePath && rawPath.startsWith(basePath) ? rawPath.slice(basePath.length) || '/' : rawPath;
        if (path === '/health' && request.method === 'GET') return json(response, { mode: process.env.CAMPAIGN_DB_MODE === 'memory' ? 'test-memory' : 'postgres-required', trustedLocalOnly: true });
        if (path === '/campaign/projection' && request.method === 'GET') return json(response, service.projection(actor));
        if (path === '/index-state' && request.method === 'GET') return json(response, service.getState(actor));
        if (path === '/index-state' && request.method === 'PUT') { const body = await readBody(request); const expected = Number(request.headers['if-match-revision'] ?? NaN); const state = service.replaceState(body, actor, Number.isInteger(expected) ? expected : undefined, typeof request.headers['idempotency-key'] === 'string' ? request.headers['idempotency-key'] : undefined); await persist?.(); return json(response, state); }
        if (path === '/campaign/docket' && request.method === 'GET') return json(response, service.memoryForApi().docket);
        if (path === '/campaign/docket' && request.method === 'POST') { const body = await readBody(request) as { activity: CampaignDocketActivity; durationDays: number; note: string; actorId: string }; const entry = service.createDocket(body, actor); await persist?.(); return json(response, entry, 201); }
        if (path.startsWith('/campaign/docket/') && path.endsWith('/supersede') && request.method === 'POST') { const body = await readBody(request) as { reason: string }; const entries = service.supersedeDocket(path.split('/')[3], body.reason, actor); await persist?.(); return json(response, entries); }
        if (path === '/campaign/legacy-adaptations' && request.method === 'GET') return json(response, service.memoryForApi().legacyAdaptations);
        if (path.startsWith('/campaign/legacy-adaptations/') && path.endsWith('/confirm') && request.method === 'POST') { const body = await readBody(request) as { campaignSettledAt: CampaignDate }; const review = service.confirmLegacyAdaptation(path.split('/')[3], body.campaignSettledAt, actor); await persist?.(); return json(response, review); }
        if (path === '/campaign/identities' && request.method === 'GET') return json(response, ['owner-gm', 'gm', 'co-gm'].includes(actor.role) ? service.memoryForApi().identities : process.env.HOSTED_MODE === 'true' ? service.memoryForApi().identities.filter((identity) => identity.id === actor.identityId) : service.memoryForApi().identities.filter((identity) => identity.role === 'player'));
        if (path === '/campaign/identities' && request.method === 'PUT') { const identities = service.setIdentities((await readBody(request)) as CampaignIdentity[], actor); await persist?.(); return json(response, identities); }
        if (path === '/campaign/control' && request.method === 'GET') return json(response, service.controlForApi(actor));
        if (path === '/campaign/world' && request.method === 'GET') return json(response, service.worldForApi(actor));
        if (path === '/campaign/world/locations' && request.method === 'POST') { const row = service.createWorldLocation((await readBody(request)) as never, actor); await persist?.(); return json(response, row, 201); }
        if (path.startsWith('/campaign/world/locations/') && request.method === 'PUT') { const row = service.updateWorldLocation(path.split('/')[4], (await readBody(request)) as never, actor); await persist?.(); return json(response, row); }
        if (path.startsWith('/campaign/world/locations/') && path.endsWith('/readiness') && request.method === 'POST') { const body = await readBody(request) as { readiness: never; reason: string }; const row = service.setWorldDossierReadiness(path.split('/')[4], body.readiness, body.reason, actor); await persist?.(); return json(response, row); }
        if (path.startsWith('/campaign/world/locations/') && path.endsWith('/promote') && request.method === 'POST') { const row = service.promoteWorldDossier(path.split('/')[4], (await readBody(request)) as never, actor); await persist?.(); return json(response, row); }
        if (path === '/campaign/world/routes' && request.method === 'POST') { const row = service.createTravelRoute((await readBody(request)) as never, actor); await persist?.(); return json(response, row, 201); }
        if (path === '/campaign/world/travel' && request.method === 'POST') { const row = service.planTravel((await readBody(request)) as { originLocationId?: string; destinationLocationId?: string; routeId?: string; participantIds: string[]; operationId?: string; note: string }, actor); await persist?.(); return json(response, row, 201); }
        if (path.startsWith('/campaign/world/travel/') && path.endsWith('/confirm') && request.method === 'POST') { const row = service.confirmTravel(path.split('/')[4], actor); await persist?.(); return json(response, row); }
        if (path.startsWith('/campaign/world/travel/') && path.endsWith('/complete') && request.method === 'POST') { const row = service.completeTravel(path.split('/')[4], actor); await persist?.(); return json(response, row); }
        if (path.startsWith('/campaign/world/travel/') && path.endsWith('/cancel') && request.method === 'POST') { const body = await readBody(request) as { reason: string }; const row = service.cancelTravel(path.split('/')[4], body.reason, actor); await persist?.(); return json(response, row); }
        if (path === '/campaign/world/hearthshield' && request.method === 'PUT') { const row = service.updateHearthshield((await readBody(request)) as never, actor); await persist?.(); return json(response, row); }
        if (path === '/campaign/world/projects' && request.method === 'POST') { const row = service.createTypedProject((await readBody(request)) as never, actor); await persist?.(); return json(response, row, 201); }
        if (path.startsWith('/campaign/world/pressures/') && request.method === 'PUT') { const row = service.updateRegionalPressure(path.split('/')[4], (await readBody(request)) as never, actor); await persist?.(); return json(response, row); }
        if (path === '/campaign/world/cold-ember' && request.method === 'PUT') { const row = service.updateColdEmber((await readBody(request)) as never, actor); await persist?.(); return json(response, row); }
        if (path === '/campaign/events' && request.method === 'POST') { const row = service.createEventRun((await readBody(request)) as { templateId: string; operationId?: string; locationId?: string; playerBriefing: string; gmTruth?: string }, actor); await persist?.(); return json(response, row, 201); }
        if (path.startsWith('/campaign/events/') && path.endsWith('/stage') && request.method === 'POST') { const body = await readBody(request) as { stageId: string; status: 'active' | 'completed' | 'failed'; reason: string }; const row = service.setEventStage(path.split('/')[3], body.stageId, body.status, body.reason, actor); await persist?.(); return json(response, row); }
        if (path.startsWith('/campaign/events/') && path.endsWith('/clock-link') && request.method === 'POST') { const body = await readBody(request) as { clockId: string; note: string }; const row = service.linkEventClock(path.split('/')[3], body.clockId, body.note, actor); await persist?.(); return json(response, row); }
        if (path.startsWith('/campaign/events/') && path.endsWith('/clock-apply') && request.method === 'POST') { const body = await readBody(request) as { clockId: string; segments: number; reason: string }; const row = service.applyEventClock(path.split('/')[3], body.clockId, body.segments, body.reason, actor); await persist?.(); return json(response, row); }
        if (path.startsWith('/campaign/events/') && request.method === 'POST') { const body = await readBody(request) as { action: 'prepare' | 'start' | 'resolve' | 'decline'; reason?: string; result?: OperationResult }; const row = service.advanceEventRun(path.split('/')[3], body.action, actor, body.reason, body.result); await persist?.(); return json(response, row); }
        if (path === '/campaign/operations' && request.method === 'GET') return json(response, service.operationsForApi(actor));
        if (path === '/campaign/operations' && request.method === 'POST') { const row = service.createOperation((await readBody(request)) as Pick<CampaignOperation, 'title' | 'system' | 'narrativePurpose' | 'statedStakes' | 'playerBriefing' | 'sourceReference' | 'participants' | 'objectives' | 'timePlan'>, actor); await persist?.(); return json(response, row, 201); }
        if (path.startsWith('/campaign/operations/under-fire/') && request.method === 'POST') { const row = service.bridgeUnderFireEvent(path.split('/')[4], actor); await persist?.(); return json(response, row, 201); }
        if (path.startsWith('/campaign/operations/') && path.endsWith('/truth') && request.method === 'POST') { const body = await readBody(request) as { truth: Omit<MissionTruthSheet, 'lockedAt' | 'corrections'>; reason?: string }; const row = service.setMissionTruth(path.split('/')[3], body.truth, actor, body.reason); await persist?.(); return json(response, row); }
        if (path.startsWith('/campaign/operations/') && path.endsWith('/prepare') && request.method === 'POST') { const row = service.prepareOperation(path.split('/')[3], actor); await persist?.(); return json(response, row); }
        if (path.startsWith('/campaign/operations/') && path.endsWith('/commit') && request.method === 'POST') { const row = service.commitOperation(path.split('/')[3], actor); await persist?.(); return json(response, row); }
        if (path.startsWith('/campaign/operations/') && path.endsWith('/start') && request.method === 'POST') { const row = service.startOperation(path.split('/')[3], actor); await persist?.(); return json(response, row); }
        if (path.startsWith('/campaign/operations/') && path.endsWith('/resolve') && request.method === 'POST') { const body = await readBody(request) as { result: OperationResult; imStages?: CampaignOperation['imStages']; reason: string }; const row = service.resolveOperation(path.split('/')[3], body, actor); await persist?.(); return json(response, row); }
        if (path.startsWith('/campaign/operations/') && path.endsWith('/void') && request.method === 'POST') { const body = await readBody(request) as { reason: string }; const row = service.voidOperation(path.split('/')[3], body.reason, actor); await persist?.(); return json(response, row); }
        if (path.startsWith('/campaign/operations/') && request.method === 'PUT') { const row = service.updateOperation(path.split('/')[3], (await readBody(request)) as Partial<CampaignOperation>, actor); await persist?.(); return json(response, row); }
        if (path.startsWith('/campaign/aftermath/') && request.method === 'POST') { const body = await readBody(request) as { decision: 'confirmed' | 'rejected'; reason: string }; const row = service.decideAftermath(path.split('/')[3], body.decision, body.reason, actor); await persist?.(); return json(response, row); }
        if (path === '/campaign/forces/profiles' && request.method === 'POST') { const row = service.createForceProfile((await readBody(request)) as Omit<ForceProfile, 'id' | 'createdAt' | 'updatedAt' | 'status'>, actor); await persist?.(); return json(response, row, 201); }
        if (path === '/campaign/forces/units' && request.method === 'POST') { const row = service.createForceUnit((await readBody(request)) as Omit<ForceUnit, 'id' | 'createdAt' | 'updatedAt' | 'availability' | 'activeHonours'>, actor); await persist?.(); return json(response, row, 201); }
        if (path === '/campaign/forces/deployments' && request.method === 'POST') { const row = service.createDeployment((await readBody(request)) as Omit<OperationDeployment, 'id'>, actor); await persist?.(); return json(response, row, 201); }
        if (path === '/campaign/forces/recoveries' && request.method === 'POST') { const body = await readBody(request) as { operationId: string; unitId: string; durationDays: number; reason: string }; const row = service.createRecovery(body, actor); await persist?.(); return json(response, row, 201); }
        if (path === '/campaign/army' && request.method === 'GET') return json(response, service.armyForApi(actor));
        if (path === '/campaign/army/rules-search' && request.method === 'GET') return json(response, service.searchRulesVault(url.searchParams.get('q') ?? '', actor));
        if (path === '/campaign/army/rules-packages' && request.method === 'POST') { const row = service.registerRulesPackage((await readBody(request)) as Omit<RulesSourcePackage, 'id' | 'importedAt'>, actor); await persist?.(); return json(response, row, 201); }
        if (path === '/campaign/army/rules-packages/sync' && request.method === 'POST') { const row = service.syncRulesVault(actor); await persist?.(); return json(response, row); }
        if (path === '/campaign/army/proposals' && request.method === 'POST') { const row = service.createCollectionProposal((await readBody(request)) as Pick<CollectionProposal, 'profileId' | 'title' | 'factionRoute' | 'approximatePoints' | 'importedLabel' | 'importId'>, actor); await persist?.(); return json(response, row, 201); }
        if (path === '/campaign/army/imports' && request.method === 'POST') { const row = service.importRoster((await readBody(request)) as { profileId: string; filename: string; contentBase64: string }, actor); await persist?.(); return json(response, row, 201); }
        if (path.startsWith('/campaign/army/proposals/') && request.method === 'POST') { const body = await readBody(request) as { decision: 'approved' | 'rejected'; reason: string }; const row = service.decideCollectionProposal(path.split('/')[4], body.decision, body.reason, actor); await persist?.(); return json(response, row); }
        if (path === '/campaign/army/rosters' && request.method === 'POST') { const row = service.createRosterDraft((await readBody(request)) as Pick<RosterDraft, 'profileId' | 'title' | 'unitIds' | 'detachmentName' | 'declaredBurdens'>, actor); await persist?.(); return json(response, row, 201); }
        if (path === '/campaign/army/attachments' && request.method === 'POST') { const row = service.setUnitAttachment((await readBody(request)) as Omit<UnitAttachment, 'id' | 'createdAt' | 'createdBy'>, actor); await persist?.(); return json(response, row, 201); }
        if (path.startsWith('/campaign/army/attachments/') && request.method === 'DELETE') { const row = service.removeUnitAttachment(path.split('/')[4], actor); await persist?.(); return json(response, row); }
        if (path === '/campaign/army/progression-requests' && request.method === 'POST') { const row = service.createProgressionRequest((await readBody(request)) as Pick<ProgressionRequest, 'unitId' | 'kind' | 'amount' | 'reason' | 'sourceType' | 'sourceId' | 'honourCardId'>, actor); await persist?.(); return json(response, row, 201); }
        if (path === '/campaign/army/honours' && request.method === 'POST') { const row = service.createHonourCard((await readBody(request)) as { title: string; xpCost: number; playerSummary: string; sourceReference: string }, actor); await persist?.(); return json(response, row, 201); }
        if (path.startsWith('/campaign/army/honours/') && request.method === 'PUT') { const body = await readBody(request) as { published: boolean }; const row = service.setHonourPublication(path.split('/')[4], body.published, actor); await persist?.(); return json(response, row); }
        if (path.startsWith('/campaign/army/progression-requests/') && request.method === 'PUT') { const body = await readBody(request) as { decision: 'approved' | 'rejected' | 'void'; reason: string; amount?: number }; const row = service.decideProgressionRequest(path.split('/')[4], body.decision, body.reason, actor, body.amount); await persist?.(); return json(response, row); }
        if (path.startsWith('/campaign/army/rosters/') && path.endsWith('/submit') && request.method === 'POST') { const row = service.submitRosterDraft(path.split('/')[4], actor); await persist?.(); return json(response, row); }
        if (path.startsWith('/campaign/army/rosters/') && request.method === 'PUT') { const body = await readBody(request) as { decision: 'approved' | 'archived'; reason: string }; const row = service.decideRosterDraft(path.split('/')[4], body.decision, body.reason, actor); await persist?.(); return json(response, row); }
        if (path === '/campaign/economy' && request.method === 'GET') return json(response, service.economyForApi(actor));
        if (path === '/campaign/control/reset' && request.method === 'POST') { if (process.env.CAMPAIGN_DB_MODE !== 'memory') return json(response, { error: 'Campaign-control reset is available only to deterministic test fixtures.' }, 404); const control = service.resetControlForTest(actor); return json(response, control); }
        if (path === '/campaign/economy/battle-award' && request.method === 'POST') { const body = await readBody(request) as { participants: number; result: 'win' | 'loss'; reason: string }; const result = service.awardBattleRp(body.participants, body.result, body.reason, actor); await persist?.(); return json(response, result, 201); }
        if (path === '/campaign/economy/award' && request.method === 'POST') { const body = await readBody(request) as { amount: number; kind: Extract<RpTransactionKind, 'liability-award' | 'exceptional-discovery' | 'exceptional-outcome' | 'correction'>; reason: string }; const result = service.awardRp(body.amount, body.kind, body.reason, actor); await persist?.(); return json(response, result, 201); }
        if (path === '/campaign/economy/convert-rp' && request.method === 'POST') { const body = await readBody(request) as { visitId: string; idempotencyKey: string }; const state = service.convertRpToTc(body.visitId, actor, body.idempotencyKey); await persist?.(); return json(response, state); }
        if (path === '/campaign/economy/requisitions' && request.method === 'POST') { const row = service.createRequisition((await readBody(request)) as Pick<CampaignRequisition, 'title' | 'kind' | 'cost' | 'source' | 'target' | 'effect'>, actor); await persist?.(); return json(response, row, 201); }
        if (path.startsWith('/campaign/economy/requisitions/') && request.method === 'POST') { const body = await readBody(request) as { status: 'approved' | 'spent' | 'void'; reason?: string }; const row = service.advanceRequisition(path.split('/')[4], body.status, actor, body.reason); await persist?.(); return json(response, row); }
        if (path === '/campaign/economy/assets' && request.method === 'POST') { const row = service.createClaimedAsset((await readBody(request)) as Omit<ClaimedAsset, 'id' | 'createdAt' | 'updatedAt' | 'audit' | 'status'>, actor); await persist?.(); return json(response, row, 201); }
        if (path.startsWith('/campaign/economy/assets/') && path.endsWith('/dispose') && request.method === 'POST') { const body = await readBody(request) as { kind: ClaimedAssetDisposition; recipientDirectoryId?: string; negotiatedRp?: number; reason: string }; const row = service.disposeClaimedAsset(path.split('/')[4], body, actor); await persist?.(); return json(response, row); }
        if (path === '/campaign/economy/discoveries' && request.method === 'POST') { const row = service.issueDiscovery((await readBody(request)) as { templateId: string; ownerMode: DiscoveryInstance['ownerMode']; ownerIdentityId?: string; publicDescription?: string; linkedEvidenceIds?: string[]; linkedAssetIds?: string[]; namedDebt?: string; nextComplication?: string }, actor); await persist?.(); return json(response, row, 201); }
        if (path.startsWith('/campaign/economy/discoveries/') && request.method === 'POST') { const body = await readBody(request) as { status: DiscoveryInstance['status']; reason: string }; const row = service.updateDiscovery(path.split('/')[4], body.status, body.reason, actor); await persist?.(); return json(response, row); }
        if (path === '/campaign/sessions' && request.method === 'POST') { const session = service.createSession((await readBody(request)) as Pick<CampaignSession, 'title' | 'purpose'>, actor); await persist?.(); return json(response, session, 201); }
        if (path.startsWith('/campaign/sessions/') && path.endsWith('/close') && request.method === 'POST') { const body = await readBody(request) as Pick<CampaignSession, 'outcomeSummary' | 'aftermath' | 'draftRecap'>; const session = service.closeSession(path.split('/')[3], body, actor); await persist?.(); return json(response, session); }
        if (path.startsWith('/campaign/sessions/') && request.method === 'PUT') { const session = service.updateSession(path.split('/')[3], (await readBody(request)) as Partial<CampaignSession>, actor); await persist?.(); return json(response, session); }
        if (path.startsWith('/campaign/sessions/') && path.endsWith('/void') && request.method === 'POST') { const body = await readBody(request) as { reason: string }; const session = service.voidSession(path.split('/')[3], body.reason, actor); await persist?.(); return json(response, session); }
        if (path === '/campaign/publications' && request.method === 'POST') { const publication = service.createPublication((await readBody(request)) as Pick<CampaignPublication, 'kind' | 'title' | 'body' | 'sourceType' | 'sourceId'>, actor); await persist?.(); return json(response, publication, 201); }
        if (path.startsWith('/campaign/publications/') && path.endsWith('/status') && request.method === 'POST') { const body = await readBody(request) as { status: CampaignPublication['status'] }; const publication = service.setPublicationStatus(path.split('/')[3], body.status, actor); await persist?.(); return json(response, publication); }
        if (path.startsWith('/campaign/publications/') && path.endsWith('/acknowledge') && request.method === 'POST') { const body = await readBody(request) as { idempotencyKey: string }; const acknowledgement = service.acknowledgePublication(path.split('/')[3], actor, body.idempotencyKey); await persist?.(); return json(response, acknowledgement, 201); }
        if (path === '/campaign/mandates' && request.method === 'POST') { const mandate = service.createMandate((await readBody(request)) as Pick<AuthorityMandate, 'title' | 'scope' | 'objectives' | 'supportRoute'>, actor); await persist?.(); return json(response, mandate, 201); }
        if (path.startsWith('/campaign/mandates/') && path.endsWith('/debrief') && request.method === 'POST') { const body = await readBody(request) as { result: AuthorityResult; debrief: string }; const mandate = service.debriefMandate(path.split('/')[3], body.result, body.debrief, actor); await persist?.(); return json(response, mandate); }
        if (path === '/campaign/rosette-invocations' && request.method === 'POST') { const invocation = service.recordRosetteInvocation((await readBody(request)) as Pick<RosetteInvocation, 'purpose' | 'consequence'>, actor); await persist?.(); return json(response, invocation, 201); }
        if (path === '/campaign/cipher/use' && request.method === 'POST') { const cipher = service.useCipher((await readBody(request)) as { sessionId: string; contact: string; category: Cipher17State['uses'][number]['category']; purpose: string; overrideReason?: string; debtOrComplication?: string }, actor); await persist?.(); return json(response, cipher); }
        if (path === '/campaign/cipher/complication' && request.method === 'POST') { const body = await readBody(request) as { detail: string }; const cipher = service.resolveCipherComplication(body.detail, actor); await persist?.(); return json(response, cipher); }
        if (path === '/campaign/cipher/refresh' && request.method === 'POST') { const body = await readBody(request) as { sessionId: string; reason: string }; const cipher = service.refreshCipher(body.sessionId, body.reason, actor); await persist?.(); return json(response, cipher); }
        if (path === '/campaign/relationships' && request.method === 'POST') { const relationship = service.updateRelationship((await readBody(request)) as Omit<NpcRelationship, 'id' | 'updatedAt' | 'effectiveDate'>, actor); await persist?.(); return json(response, relationship, 201); }
        if (path === '/campaign/corruption-edges' && request.method === 'POST') { const edge = service.addCorruptionEdge((await readBody(request)) as Omit<CorruptionWebEdge, 'id' | 'createdAt' | 'updatedAt'>, actor); await persist?.(); return json(response, edge, 201); }
        if (path.startsWith('/campaign/influence/') && request.method === 'POST') { const body = await readBody(request) as { kind: 'influence' | 'favour'; amount: number; reason: string; sourceType?: string; sourceId?: string }; const track = service.adjustInfluence(path.split('/')[3], body.kind, body.amount, body.reason, actor, body.sourceType, body.sourceId); await persist?.(); return json(response, track); }
        if (path === '/campaign/evidence' && request.method === 'POST') { const evidence = service.createEvidence((await readBody(request)) as Omit<EvidenceRecord, 'id' | 'custody' | 'createdAt' | 'updatedAt'>, actor); await persist?.(); return json(response, evidence, 201); }
        if (path.startsWith('/campaign/evidence/') && path.endsWith('/custody') && request.method === 'POST') { const body = await readBody(request) as { custodian: string; reason: string; sourceType?: string; sourceId?: string }; const evidence = service.transferEvidenceCustody(path.split('/')[3], body.custodian, body.reason, actor, body.sourceType, body.sourceId); await persist?.(); return json(response, evidence); }
        if (path === '/campaign/mysteries' && request.method === 'POST') { const mystery = service.createMystery((await readBody(request)) as Omit<import('../src/types').MysteryRecord, 'id' | 'createdAt' | 'updatedAt'>, actor); await persist?.(); return json(response, mystery, 201); }
        if (path === '/campaign/debts' && request.method === 'POST') { const debt = service.createDebt((await readBody(request)) as Omit<CampaignDebt, 'id' | 'createdAt' | 'updatedAt'>, actor); await persist?.(); return json(response, debt, 201); }
        if (path === '/campaign/hooks' && request.method === 'POST') { const hook = service.createHook((await readBody(request)) as Omit<CampaignHook, 'id' | 'createdAt' | 'updatedAt'>, actor); await persist?.(); return json(response, hook, 201); }
        if (path === '/campaign/sources' && request.method === 'GET') return json(response, service.searchSources(url.searchParams.get('q') ?? ''));
        if (path === '/campaign/backup' && request.method === 'POST') return json(response, service.exportCampaign(actor), 201);
        if (path === '/campaign/restore-preview' && request.method === 'POST') return json(response, service.previewRestore(await readBody(request), actor));
        return json(response, { error: 'Unknown campaign API endpoint.' }, 404);
      } catch (failure) { return error(response, failure); }
  };
}

/** Development transport only; production uses production-server.ts. */
export function campaignApi(service: CampaignService, persist?: () => Promise<void>, actorResolver: ApiActorResolver = trustedLocalActorFrom): Plugin {
  return { name: 'gilded-index-campaign-api', configureServer(server) { server.middlewares.use('/api', campaignApiHandler(service, persist, actorResolver)); } };
}
