import type { AtlasLocation, AtlasSignal } from '../src/features/atlas/atlas-types';

/**
 * Public Atlas records only. These are deliberately separate from the former
 * campaign-control seed: no source paths, GM notes, contacts, routes, travel
 * records, assets, evidence, or unpublished pressure state are present here.
 */
export const atlasLocations: readonly AtlasLocation[] = [
  { id: 'location-uzazaban', title: 'Uzazaban — The Red Marches', mapLabel: 'Uzazaban', mapPosition: { x: 92, y: 23.5 }, detailStatus: 'dossier', publicDescription: 'An industrial death world rebuilt around surviving the Peregrine Scar.', authorityAccess: 'Provisional military rule under General Sera Halden.', consequences: [] },
  { id: 'location-ex-morvan', title: 'Ex Morvan', mapLabel: 'Ex Morvan', mapPosition: { x: 81, y: 38 }, detailStatus: 'dossier', publicDescription: 'A controlled quarantine world of sanctified battlefields, ruins, and contested salvage permits.', authorityAccess: 'Purpose, screening, and a defensible chain of custody are required.', consequences: [] },
  { id: 'location-calverna', title: 'Calverna', mapLabel: 'Calverna', mapPosition: { x: 52, y: 24.5 }, detailStatus: 'dossier', publicDescription: 'Tavrellis’s visible engine of rebuilding: salvage yards, refineries, repair docks, labour districts, and half-restored manufactoria.', authorityAccess: 'Industrial clearance, labour sponsorship, and salvage authority are required.', consequences: [] },
  { id: 'location-eonope', title: 'Eonope', mapLabel: 'Eonope', mapPosition: { x: 70.5, y: 13.5 }, detailStatus: 'dossier', publicDescription: 'A vital source of food, water, medicine, refuge, and logistical support for Tavrellis.', authorityAccess: 'Supply authority, civic cooperation, and biosecurity screening are required near life-support infrastructure.', consequences: [] },
  { id: 'location-iscara', title: 'Iscara', mapLabel: 'Iscara', mapPosition: { x: 67.5, y: 35.3 }, detailStatus: 'dossier', publicDescription: 'A lava planet of magma fields, unstable crust, poisoned atmosphere, and heat-scarred manufactoria.', authorityAccess: 'Hazard certification, thermal equipment, and controlled recovery permits are mandatory.', consequences: [] },
  { id: 'location-warp-meridian', title: 'Warp Meridian', mapLabel: 'Warp Meridian', mapPosition: { x: 62.5, y: 57 }, detailStatus: 'dossier', publicDescription: 'A physical and spiritual scar left after the destruction of a Chaos rift power source.', authorityAccess: 'Containment clearance, recovery escorts, and route-condition confirmation are mandatory.', consequences: [] },
  { id: 'location-auroria', title: 'Auroria', mapLabel: 'Auroria', mapPosition: { x: 91, y: 46 }, detailStatus: 'dossier', publicDescription: 'The former core of Marauder power, marked by xenos structures, occupation works, and a vast ruined tomb.', authorityAccess: 'Occupation-remnant salvage, xenos-containment, and tomb-exclusion authorities overlap.', consequences: [] },
  { id: 'location-gork', title: 'Gork', mapLabel: 'Gork', mapPosition: { x: 49, y: 57 }, detailStatus: 'dossier', publicDescription: 'A reclaimed Ork world carrying the scars of liberation and abandoned wartime installations.', authorityAccess: 'Settlement councils, liberation authorities, and security commands all claim jurisdiction.', consequences: [] },
  { id: 'location-carthax', title: 'Carthax', mapLabel: 'Carthax', mapPosition: { x: 81, y: 53 }, detailStatus: 'dossier', publicDescription: 'A damaged orbital-industrial world of shipyard remnants, dead manufactoria, and technical recovery sites.', authorityAccess: 'Technical authority, voidyard safety clearance, and salvage manifests are required.', consequences: [] },
  { id: 'location-orison', title: 'Orison', mapLabel: 'Orison', mapPosition: { x: 31.5, y: 63.5 }, detailStatus: 'dossier', publicDescription: 'A shrine and memorial world where pilgrims, refugees, veterans, and claimants contest how Tavrellis should remember.', authorityAccess: 'Pilgrim conduct, shrine authority, and memorial-custody permission are expected.', consequences: [] },
  { id: 'location-alecto', title: 'Alecto', mapLabel: 'Alecto', mapPosition: { x: 54, y: 62 }, detailStatus: 'dossier', publicDescription: 'Tavrellis’s administrative memory: registries, charters, inheritance claims, and records of authority.', authorityAccess: 'Archive recovery warrants, claimant cooperation, and strict chain-of-custody records are expected.', consequences: [] },
  { id: 'location-khelt', title: 'Khelt', mapLabel: 'Khelt', mapPosition: { x: 85, y: 61 }, detailStatus: 'dossier', publicDescription: 'A bitterly cold muster world carrying the cost of the war in depleted settlements and missing formations.', authorityAccess: 'Winter transit readiness, settlement approval, and military record clearance are needed beyond main stations.', consequences: [] },
  { id: 'location-xill', title: 'Xill', mapLabel: 'Xill', mapPosition: { x: 48, y: 71.5 }, detailStatus: 'dossier', publicDescription: 'A heavy mining world where routine extraction reaches collapsed undercities and sealed deep strata.', authorityAccess: 'Mining permits, excavation safety certification, and local claimant clearance govern access.', consequences: [] },
  { id: 'location-cthon', title: 'Cthon', mapLabel: 'Cthon', mapPosition: { x: 63, y: 73 }, detailStatus: 'dossier', publicDescription: 'A violent ocean world of storm belts, platforms, isolated settlements, and difficult salvage.', authorityAccess: 'Weather windows, platform sponsorship, and maritime rescue protocols are essential.', consequences: [] },
  { id: 'location-pyraxis', title: 'Pyraxis', mapLabel: 'Pyraxis', mapPosition: { x: 72.5, y: 75 }, detailStatus: 'dossier', publicDescription: 'A vast jungle world whose resource-rich flora and wildlife remain lethally altered by lingering warp influence.', authorityAccess: 'Biosecurity clearance, guided routes, and preservation rules are required.', consequences: [] },
  { id: 'location-noxara', title: 'Noxara', mapLabel: 'Noxara', mapPosition: { x: 45, y: 86 }, detailStatus: 'dossier', publicDescription: 'An ice-bound frontier world with thin patrol coverage, difficult survival, and old listening posts.', authorityAccess: 'Cold-weather readiness, survival logistics, and patrol coordination are required.', consequences: [] },
];

/** Only reports explicitly cleared as player-facing urgent signals belong here. */
export const atlasUrgentSignals: readonly AtlasSignal[] = [];
export const atlasCampaignDate = 'M7 D5, 412.M42';
