import type { ColdEmberLedger, EventTemplate, RegionalPressure, TravelRoute, TypedProject, WorldLocation } from '../src/types';

const source = '02 Event Compendium/Imperium Maledictum Campaign Events.docx';
const created = '2026-09-04T00:00:00.000Z';

const event = (id: string, title: string, stages: string[]): EventTemplate => ({
  id, title, version: 1, sourceReference: source, systems: ['imperium-maledictum', 'kill-team', 'warhammer-40000'],
  publicBriefing: 'A campaign event is developing. Your Cell receives only the briefing the GM elects to publish.',
  gmTruth: 'Refer to the canonical Event Compendium framework; this runner preserves GM control of consequences.',
  stages: stages.map((stage, index) => ({ id: `${id}-stage-${index + 1}`, title: stage, publicSummary: stage, gmGuidance: 'Use the named canonical event stage and its escalation guidance.' })),
  declineGuidance: 'Record the Cell’s decision and the resulting contained, partial, or failed consequence explicitly.',
  aftermathGuidance: 'Resolve only GM-confirmed aftermath through the existing campaign services.', active: true, createdAt: created, updatedAt: created,
});

export const eventTemplateSeeds: EventTemplate[] = [
  event('event-unburning-legion', 'The Unburning Legion', ['The Impossible Rescue', 'The Afterimage', 'The Inquest', 'The Choice of Allegiance']),
  event('event-hives-last-breath', "The Hive's Last Breath", ['Survey the Organism', 'Arm the Charges', 'Sabotage Revealed', 'Run the Gauntlet']),
  event('event-green-tide-crossfire', 'Green Tide at the Crossfire', ['A Bad Auspex Return', 'Third-Party Entry', 'The Crossfire', 'The Cost of Escape']),
  event('event-faithless-reserve', 'The Faithless Reserve', ['The Missing Muster', 'The Cinder Witnesses', 'The Reserve Choice', 'The Record That Remains']),
  event('event-orders-assassin', 'Orders for the Assassin', ['The Assignment', 'The Target', 'The Competing Order', 'The Consequence']),
  event('event-lie-briefing', 'The Lie in the Briefing', ['The False Brief', 'The Altered Manifest', 'The Split Authority', 'The Record Recovered']),
];

const mapSource = '08 Maps/Tavrellis System - Named Map.png';
// Normalised, manually reviewed planet-centre positions for the source Tavrellis
// map. These deliberately follow the bodies, never its baked-in text labels.
const mapPositions: Record<string, { x: number; y: number }> = {
  eonope: { x: 70.5, y: 13.5 }, calverna: { x: 52, y: 24.5 }, uzazaban: { x: 92, y: 23.5 }, iscara: { x: 67.5, y: 35.3 }, 'ex-morvan': { x: 81, y: 38 }, auroria: { x: 91, y: 46 }, carthax: { x: 81, y: 53 }, 'warp-meridian': { x: 62.5, y: 57 }, gork: { x: 49, y: 57 }, orison: { x: 31.5, y: 63.5 }, alecto: { x: 54, y: 62 }, khelt: { x: 85, y: 61 }, xill: { x: 48, y: 71.5 }, cthon: { x: 63, y: 73 }, pyraxis: { x: 72.5, y: 75 }, noxara: { x: 45, y: 86 },
};
const mapWorld = (id: string, title: string): WorldLocation => ({ id, title, publicDescription: 'A named body on the Tavrellis system map. A complete dossier has not yet been approved.', gmSecrets: 'System-map entry only; add GM location truth when this world enters play.', authorityAccess: 'No standing access arrangement has been recorded.', contacts: [], activePressures: [], consequences: [], linkedEvidenceIds: [], linkedAssetIds: [], handoutPaths: [], artPaths: [], sourceReferences: [mapSource], mapPosition: mapPositions[id.replace('location-', '')], detailStatus: 'map-only', readiness: 'map-only', publicationStatus: 'published', createdAt: created, updatedAt: created, audit: [{ at: created, action: 'seeded-from-system-map' }] });
const workshopDossier = (id: string, title: string, subtitle: string, publicDescription: string, gmSecrets: string, authorityAccess: string, activePressures: string[]): WorldLocation => {
  const sourcePath = `06 Locations/${title} - ${subtitle}.docx`;
  return { ...mapWorld(id, title), publicDescription, gmSecrets, authorityAccess, activePressures, sourceReferences: [mapSource, sourcePath], detailStatus: 'dossier', readiness: 'published-dossier', dossierApproval: { sourcePath, basis: 'gm-approved-workshop', approvedAt: '2026-09-06T00:00:00.000Z', approvedBy: 'tavrellis-system-workshop', version: 1 }, audit: [{ at: '2026-09-06T00:00:00.000Z', action: 'approved-workshop-dossier', reason: 'GM approved the Tavrellis system workshop dossier.' }] };
};

export const locationSeeds: WorldLocation[] = [
  { id: 'location-uzazaban', title: 'Uzazaban — The Red Marches', publicDescription: 'An industrial death world rebuilt around surviving the Peregrine Scar.', gmSecrets: 'See the canonical Uzazaban location dossier.', authorityAccess: 'Provisional military rule under General Sera Halden.', contacts: ['General Sera Halden', 'Mireya Dhal', 'Nessa Veyr', 'Lycinia Quist'], activePressures: ['Peregrine Scar', 'reconstruction claims', 'route reliability'], consequences: [], linkedEvidenceIds: [], linkedAssetIds: [], handoutPaths: [], artPaths: [], sourceReferences: ['06 Locations/Uzazaban - The Peregrine Scar.docx'], mapPosition: mapPositions.uzazaban, detailStatus: 'dossier', readiness: 'published-dossier', dossierApproval: { sourcePath: '06 Locations/Uzazaban - The Peregrine Scar.docx', basis: 'existing-source', approvedAt: created, approvedBy: 'campaign-source-migration', version: 1 }, publicationStatus: 'published', createdAt: created, updatedAt: created, audit: [{ at: created, action: 'seeded' }] },
  { id: 'location-ex-morvan', title: 'Ex Morvan', publicDescription: 'A controlled quarantine world of sanctified battlefields, ruins, and contested salvage permits.', gmSecrets: 'See the canonical Ex Morvan location dossier.', authorityAccess: 'Purpose, screening, and chain of custody are required.', contacts: ['Inquisitor Orest Valecourt'], activePressures: ['quarantine', 'custody', 'recovery archive'], consequences: [], linkedEvidenceIds: [], linkedAssetIds: [], handoutPaths: [], artPaths: [], sourceReferences: ['06 Locations/Ex Morvan - Quarantine World.docx'], mapPosition: mapPositions['ex-morvan'], detailStatus: 'dossier', readiness: 'published-dossier', dossierApproval: { sourcePath: '06 Locations/Ex Morvan - Quarantine World.docx', basis: 'existing-source', approvedAt: created, approvedBy: 'campaign-source-migration', version: 1 }, publicationStatus: 'published', createdAt: created, updatedAt: created, audit: [{ at: created, action: 'seeded' }] },
  workshopDossier('location-calverna', 'Calverna', 'The Reclamation World', 'Calverna is the visible engine of rebuilding: salvage yards, refineries, repair docks, labour districts, and half-restored manufactoria. Tavrellis needs its output, yet its people are exhausted by permanent emergency.', 'A reconstruction consortium is concealing unsafe recovered material, compromised labour arrangements, and shortcuts that could carry Chaos contamination into the rebuilt system.', 'Industrial clearance, labour sponsorship, and salvage authority are required. Work zones change status rapidly as recovery crews open or close facilities.', ['Labour unrest', 'Mechanicus and civilian control conflict', 'Contaminated recovery material']),
  workshopDossier('location-eonope', 'Eonope', 'The Lifeline', 'Eonope sustains Tavrellis through food, water, medicine, refuge, and logistical support. Its stability is indispensable and its resources are targets for every emergency claim.', 'Something beneath essential infrastructure is influencing supply patterns and may be connected to the system’s older buried inheritance.', 'Supply authority, local civic cooperation, and biosecurity screening are required near life-support and production infrastructure.', ['Ration politics', 'Convoy vulnerability', 'Infrastructure contamination scares']),
  workshopDossier('location-iscara', 'Iscara', 'The Furnace Remnant', 'Iscara was a prosperous forge world before an ancient catastrophe turned it into a lava planet. Magma fields, unstable crust, poison atmosphere, and heat-scarred manufactoria make recovery slow and exceptionally hazardous.', 'The original event that transformed Iscara remains unresolved. The war’s warp contamination may be interacting with the same underlying cause.', 'Hazard certification, thermal equipment, and controlled recovery permits are mandatory. Most operational windows are short and route-specific.', ['Warp-tainted atmosphere', 'Slow reclamation', 'Unstable industrial strata']),
  workshopDossier('location-warp-meridian', 'Warp Meridian', 'The Rift Scar', 'Warp Meridian is where united Chaos forces deliberately opened a rift in an attempt to claim Tavrellis. The breach is closed and its power source destroyed, but bombardment and reclamation damage have left a physical and spiritual scar.', 'Destroying the power source ended the rift but did not erase every ritual site, cult network, corrupted archive, or dormant asset created to support the invasion.', 'Containment clearance, recovery escorts, and route-condition confirmation are mandatory. Many zones remain restricted after bombardment and failed reclamation attempts.', ['Bombarded ruins', 'Residual warp contamination', 'Compromised navigation and containment records']),
  workshopDossier('location-auroria', 'Auroria', 'The Marauder Crown', 'Auroria was the core of Marauder power during the war. Their defeat left xenos structures, technology, occupation works, residual Chaos energy, and a vast ruined Necron tomb visible from miles away.', 'The tomb awakened during the war, fought, and was partially destroyed when its occupants retreated. Automated facilities and mindless machines remain, while one surviving intelligence seeks control of the ruins.', 'Occupation-remnant salvage, xenos-containment, and tomb-exclusion authorities overlap. Every expedition needs explicit authority and a defensible custody plan.', ['Marauder technology recovery', 'Residual Chaos energy', 'Damaged Necron automated systems']),
  workshopDossier('location-gork', 'Gork', 'The Reclaimed World', 'Gork was an Ork world reclaimed by the Imperium before the war. It fell to the Marauders during the conflict, then was liberated before the war ended.', 'The Marauders were searching for or containing something in Gork’s older war-scarred depths. Their abandoned installations contain fragments of that purpose.', 'Liberation authorities, settlement councils, and security commands all claim jurisdiction. Unexploded ordnance and unstable legacy infrastructure make casual travel unsafe.', ['Contested liberation authority', 'Abandoned Marauder installations', 'Unstable Ork infrastructure']),
  workshopDossier('location-carthax', 'Carthax', 'The Silent Forge', 'Carthax is a damaged orbital-industrial world of shipyard remnants, dead manufactoria, and technical recovery sites. It could restore Tavrellis’s strategic capability, but its reconstruction will decide who controls the tools of war.', 'Several technically recoverable installations are politically impossible to restore openly. Their ownership and intended use matter as much as their condition.', 'Technical authority, voidyard safety clearance, and salvage manifests are required. Much of the orbital infrastructure remains unpowered or unstable.', ['Shipyard custody', 'Strategic reconstruction authority', 'Dead manufactoria hazards']),
  workshopDossier('location-orison', 'Orison', 'The Broken Pilgrimage', 'Orison is a shrine and memorial world whose religious importance survived the war even as its institutions fractured. Pilgrims, refugees, veterans, and claimants seek meaning there while competing authorities argue over what Tavrellis should remember.', 'Different custodians hold incompatible accounts of key wartime sacrifices. At least one public memorial protects a useful lie whose exposure could either heal or destabilise the system.', 'Pilgrim conduct, shrine authority, and memorial-custody permission are expected. Refuge districts and sacred sites have different local rules.', ['Fractured shrine authority', 'Refuge and memorial claims', 'Competing wartime narratives']),
  workshopDossier('location-alecto', 'Alecto', 'The Memory Seat', 'Alecto was Tavrellis’s administrative memory before the war: registries, charters, inheritance claims, and records of authority. Its surviving archives now decide who may rebuild, command, inherit, and recover.', 'Some archives were deliberately removed because they reveal pre-war agreements connected to the system’s buried relic network.', 'Archive recovery warrants, local claimant cooperation, and strict chain-of-custody records are expected. Emergency military authority remains contested.', ['Forged reconstruction warrants', 'Rival archive custody claims', 'A sealed memorial district']),
  workshopDossier('location-khelt', 'Khelt', 'The Frozen Muster', 'Khelt is a bitterly cold snow world whose people carried a disproportionate share of the war. Depleted settlements, missing formations, veterans, and military infrastructure endure in an environment that makes recovery expensive and slow.', 'Some missing formations and wartime reserves were redirected or erased for reasons that would threaten the legitimacy of current command if exposed.', 'Winter transit readiness, local settlement approval, and military record clearance are needed beyond the main stations.', ['Veteran exhaustion', 'Missing formations', 'Permanent manpower-requisition pressure']),
  workshopDossier('location-xill', 'Xill', 'The Underworld Archive', 'Xill is Tavrellis’s heavy mining world: deep excavations, ore lifters, collapsed undercities, and sealed strata sit beneath an industrial surface that never truly sleeps. Routine extraction frequently becomes historical recovery when crews uncover structures that should not exist beneath the rock.', 'Several deep sites preserve records and mechanisms tied to Tavrellis’s older buried inheritance. Competing recovery teams do not understand that they are opening parts of the same system-wide puzzle.', 'Mining permits, excavation safety certification, and clearance from local claimants govern access. Deep zones can change status without warning.', ['Collapsed undercities', 'Competing excavation claims', 'Sealed deep strata']),
  workshopDossier('location-cthon', 'Cthon', 'The Stormwater World', 'Cthon is a violent oceanic world of storm belts, platforms, isolated settlements, and difficult salvage. Its weather keeps communities self-reliant and makes system control fragile.', 'The sea conceals wartime losses and older structures that surface only after particular storms. Some salvage traffic may be following information no public chart contains.', 'Weather windows, platform sponsorship, and maritime rescue protocols are essential. Local crews decide whether most routes are survivable.', ['Storm-belt isolation', 'Platform survival', 'Uncharted salvage traffic']),
  workshopDossier('location-pyraxis', 'Pyraxis', 'The Verdant Mutation', 'Pyraxis is a vast jungle world and former core of the Forces of Change. Its flora and wildlife are beautiful, resource-rich, and lethally dangerous. Tzeentch’s lingering influence still distorts life throughout the planet.', 'The mutation is not merely residual contamination. Some ecosystems are adapting around it in ways that may be valuable, infectious, intelligent, or deliberately shaped by surviving Tzeentch influence.', 'Biosecurity clearance, guided routes, and preservation rules are required. Reclamation teams must balance extraction against ecological collapse and mutation spread.', ['Mutated flora and wildlife', 'Natural-resource exploitation', 'Tzeentch contamination']),
  workshopDossier('location-noxara', 'Noxara', 'The Icebound Frontier', 'Noxara is an ice-bound dark frontier world where weak patrol coverage, difficult survival, and old wartime listening posts leave Tavrellis exposed.', 'Some listening posts were not abandoned cleanly. Their remaining data may reveal xenos movement, hidden approaches, or evidence that someone has been using the frontier without Imperial knowledge.', 'Cold-weather readiness, survival logistics, and patrol coordination are required. Outlying facilities often operate beyond reliable support.', ['Thin patrol coverage', 'Icebound isolation', 'Unaccounted wartime listening posts']),
];

const route = (id: string, title: string, originLocationId: string, destinationLocationId: string, durationDays: number): TravelRoute => ({ id, title, originLocationId, destinationLocationId, publicDescription: 'An approximate navigable in-system lane. Use declared waypoints rather than assuming unrestricted direct passage.', transitBand: 'Approximate system corridor', durationDays, accessRequirements: 'Confirm current clearance, route conditions, and any world-specific restrictions.', gmPressure: 'This is a map-based estimate. Add local threats, inspections, and route interruptions only when established in play.', sourceReference: mapSource, publicationStatus: 'published', createdAt: created, updatedAt: created, audit: [{ at: created, action: 'seeded-from-system-map' }] });

// The map seeds a connected corridor network rather than every possible pair.
// A route represents a declared lane usable in either direction; longer travel
// should use multiple legs, preserving meaningful waypoints and campaign time.
export const travelRouteSeeds: TravelRoute[] = [
  route('route-calverna-eonope', 'Calverna–Eonope Corridor', 'location-calverna', 'location-eonope', 2),
  route('route-eonope-uzazaban', 'Eonope–Uzazaban Transit', 'location-eonope', 'location-uzazaban', 2),
  route('route-uzazaban-iscara', 'Uzazaban–Iscara Transit', 'location-uzazaban', 'location-iscara', 3),
  route('route-iscara-ex-morvan', 'Iscara–Ex Morvan Transfer', 'location-iscara', 'location-ex-morvan', 2),
  route('route-ex-morvan-auroria', 'Ex Morvan–Auroria Corridor', 'location-ex-morvan', 'location-auroria', 2),
  route('route-auroria-carthax', 'Auroria–Carthax Transit', 'location-auroria', 'location-carthax', 2),
  route('route-carthax-khelt', 'Carthax–Khelt Passage', 'location-carthax', 'location-khelt', 3),
  route('route-khelt-pyraxis', 'Khelt–Pyraxis Transit', 'location-khelt', 'location-pyraxis', 3),
  route('route-pyraxis-cthon', 'Pyraxis–Cthon Passage', 'location-pyraxis', 'location-cthon', 2),
  route('route-cthon-xill', 'Cthon–Xill Corridor', 'location-cthon', 'location-xill', 2),
  route('route-xill-noxara', 'Xill–Noxara Transit', 'location-xill', 'location-noxara', 2),
  route('route-noxara-orison', 'Noxara–Orison Long Passage', 'location-noxara', 'location-orison', 4),
  route('route-orison-gork', 'Orison–Gork Transit', 'location-orison', 'location-gork', 2),
  route('route-gork-warp-meridian', 'Gork–Warp Meridian Passage', 'location-gork', 'location-warp-meridian', 3),
  route('route-warp-meridian-alecto', 'Warp Meridian–Alecto Corridor', 'location-warp-meridian', 'location-alecto', 2),
  route('route-alecto-calverna', 'Alecto–Calverna Long Passage', 'location-alecto', 'location-calverna', 4),
];

export const hearthshieldSeed: TypedProject = { id: 'project-hearthshield', templateId: 'hearthshield', title: 'The Hearthshield Project', status: 'inactive', tracks: [{ id: 'forecast-integrity', title: 'Forecast Integrity', value: 0, maximum: 3 }, { id: 'corridor-security', title: 'Corridor Security', value: 0, maximum: 3 }], contactStates: [{ id: 'civil-mandate', title: 'Civil Mandate', active: false, detail: 'Available only through Mireya Dhal’s civilian-ration lead; it enables refuge and local warning, not Corridor Security.' }, { id: 'route-debt', title: 'Route Debt', active: false, detail: 'Only Oris Kelm’s accepted off-record requisition can establish Corridor Security 1 when none exists.' }], controlState: 'No initial operational control selected.', accordAvailable: false, stationStatus: 'Unactivated', breachFronts: [], activationHistory: [], sourceReferences: ['01 Adventures/The Hearthshield Project - Uzazaban Campaign Arc.docx'], updatedAt: created, audit: [{ at: created, action: 'seeded' }] };

export const regionalPressureSeeds: RegionalPressure[] = [
  { id: 'pressure-uzazaban-scar', locationId: 'location-uzazaban', kind: 'scar-activity', title: 'Scar Activity', currentStatus: 'Distant', severity: 0, publicSummary: 'The Peregrine Scar shifts routes, conditions, and opportunities across the Red Marches.', gmNotes: '', sourceReference: '06 Locations/Uzazaban - The Peregrine Scar.docx', published: true, playerFacingUrgent: false, updatedAt: created, audit: [{ at: created, action: 'seeded' }] },
  { id: 'pressure-uzazaban-command', locationId: 'location-uzazaban', kind: 'command-training', title: 'Command & Training Posture', currentStatus: 'Provisional military rule', publicSummary: 'Command, training, and reconstruction priorities remain under pressure.', gmNotes: '', sourceReference: '06 Locations/Uzazaban - The Peregrine Scar.docx', published: false, playerFacingUrgent: false, updatedAt: created, audit: [{ at: created, action: 'seeded' }] },
  { id: 'pressure-ex-morvan-quarantine', locationId: 'location-ex-morvan', kind: 'quarantine-custody', title: 'Quarantine Access & Custody', currentStatus: 'Restricted', publicSummary: 'Access depends on purpose, screening, and defensible chain of custody.', gmNotes: '', sourceReference: '06 Locations/Ex Morvan - Quarantine World.docx', published: true, playerFacingUrgent: false, updatedAt: created, audit: [{ at: created, action: 'seeded' }] },
  { id: 'pressure-ex-morvan-exchange', locationId: 'location-ex-morvan', kind: 'technical-exchange', title: 'Technical Exchange', currentStatus: 'Case-by-case', publicSummary: 'Dangerous recoveries may be exchanged for containment or research assistance.', gmNotes: '', sourceReference: '06 Locations/Ex Morvan - Quarantine World.docx', published: false, playerFacingUrgent: false, updatedAt: created, audit: [{ at: created, action: 'seeded' }] },
];

export const coldEmberSeed: ColdEmberLedger = { id: 'cold-ember', phase: 'Phase I: Ashes and Ledgers', transitionAvailability: 'GM review required; the arc is a menu of pressure, never a required sequence.', protectedParties: [], evidenceDisposition: 'Undecided', compactsOwed: [], historyVersions: [], resourcesLost: [], sabineSecretKnownBy: [], miniatureMilestones: [], endingPossibilities: [], decisions: [], updatedAt: created };
