import { BookOpenCheck } from 'lucide-react';
import type { CatalogueItem, Lot } from '../types';
import { categoryTitle, fieldAssetRule, mirenIntroduction } from '../market';

export function Dossier({ item, lot, onClose }: { item: CatalogueItem; lot: Lot; onClose: () => void }) {
  const price = `${item.price.tc} TC${item.price.rp ? ` + ${item.price.rp} RP` : ''}${item.price.auction ? ' minimum bid' : ''}`;
  const honourRecord = (item.fullDossier ?? []).filter((line) => !line.startsWith('Classification:') && !line.startsWith('Eligibility:') && !line.startsWith('Lore:'));
  return <div className="dossier-overlay" role="dialog" aria-modal="true"><article className="dossier"><button className="archive-seal" onClick={onClose} title="Reseal archive dossier"><BookOpenCheck/></button><p className="eyebrow">Miren Quill // sealed register entry</p><h2>{item.name}</h2><div className="dossier-stats"><span>{categoryTitle(lot.pool)}</span><strong>{price}</strong></div><section><h3>Claimant's Notice</h3><p>{mirenIntroduction(item)}</p></section><section><h3>Chain of Custody</h3><p>{item.origin}</p></section>{item.pool === 'field' && <section><h3>Operational Condition</h3><p>{fieldAssetRule}</p></section>}{item.battleHonour ? <section className="battle-honour"><h3>Battle Honour Record</h3><p><strong>{item.battleHonour.tier}</strong>{item.battleHonour.crusadePoints ? ` · ${item.battleHonour.crusadePoints}` : ''} · {item.battleHonour.eligibility}</p>{item.battleHonour.lore && <p>{item.battleHonour.lore}</p>}{honourRecord.length ? honourRecord.map((line) => <p key={line}>{line}</p>) : item.battleHonour.levels.map((level) => <p key={level.title}><strong>{level.title}:</strong> {level.text}</p>)}</section> : <section><h3>Certified Use</h3><p>{item.rules}</p></section>}{item.franchiseTags?.length ? <section><h3>Registry Classification</h3><p>{item.franchiseTags.join(' · ')}</p></section> : null}{lot.claimants?.length ? <section><h3>Observed Claimants</h3><div className="claimant-list">{lot.claimants.map((claimant) => <span key={claimant.name} className={`interest ${claimant.interest.toLowerCase()}`}>{claimant.name} · {claimant.interest}</span>)}</div></section> : null}<footer>Register lot {lot.position} · Miren Quill, First Factor</footer></article></div>;
}
