import { useState } from 'react';
import { defaultObjectiveRecipients, issueObjective, presentObjective, redeemObjectiveInState } from '../../market';
import type { MarketState, ObjectiveOffer, Visit } from '../../types';
import { errorText } from '../../ui/ErrorDialog';
import { useMarketCommit } from '../../ui/CommitContext';
import { Modal } from '../../components/MarketModal';

const fail = (report: (message: string) => void, error: unknown) => { const text = errorText(error); report(text); dispatchEvent(new CustomEvent('gilded-index-error', { detail: text })); };

export function ObjectiveRegister({ visit, state, setVisit, report }: { visit: Visit; state: MarketState; setVisit: (visit: Visit) => void; report: (text: string) => void }) {
  const [open, setOpen] = useState(false); const commit = useMarketCommit(); const recipients = (state.objectiveOfferRecipients ?? defaultObjectiveRecipients).filter(recipient => recipient.active && recipient.canOfferObjectives);
  const redeem = (objectiveId: string, offerId: string) => void commit(redeemObjectiveInState(state, visit.id, objectiveId, offerId)).catch(error => fail(report, error));
  return <section id="objectives" className="objectives"><div className="section-heading"><div><p className="eyebrow">GM-only rewards</p><h2>Bonus Objective Register</h2></div><button onClick={() => setOpen(true)}>Issue Bonus Objective</button></div>{(visit.objectiveRecords ?? []).map(objective => <article key={objective.id}><strong>{objective.title}</strong> · {objective.state}{objective.state === 'recorded' && <button onClick={() => { try { setVisit(presentObjective(visit, objective.id)); } catch (error) { fail(report, error); } }}>Present to players</button>}{objective.state === 'presented' && <select defaultValue="" onChange={event => event.target.value && redeem(objective.id, event.target.value)}><option value="">Record accepted offer…</option>{objective.offers.filter(offer => offer.enabled !== false).map(offer => <option key={offer.id} value={offer.id}>{offer.recipientName}: {offer.playerText}</option>)}</select>}</article>)}{open && <ObjectiveModal recipients={recipients} close={() => setOpen(false)} save={(title, summary, offers) => { try { setVisit(issueObjective(visit, title, summary, offers)); setOpen(false); } catch (error) { fail(report, error); } }}/>}</section>;
}

function ObjectiveModal({ recipients, close, save }: { recipients: NonNullable<MarketState['objectiveOfferRecipients']>; close: () => void; save: (title: string, summary: string, offers: ObjectiveOffer[]) => void }) {
  const [title, setTitle] = useState(''); const [summary, setSummary] = useState(''); const [rows, setRows] = useState<ObjectiveOffer[]>(() => recipients.map((recipient, index) => ({ id: `offer-${Date.now()}-${index}`, recipientId: recipient.id, recipientName: recipient.name, recipientType: recipient.type, rewardType: recipient.type === 'index' ? 'tc' : 'narrative', amount: recipient.type === 'index' ? 1 : undefined, detail: recipient.type === 'index' ? 'Trade Coin' : 'GM-defined reward', playerText: recipient.type === 'index' ? 'The Gilded Index offers Trade Coin.' : 'Offer available.' })));
  const change = (id: string, key: keyof ObjectiveOffer, value: string | number | boolean) => setRows(current => current.map(row => row.id === id ? { ...row, [key]: value } : row));
  const add = () => setRows(current => [...current, { id: `offer-${Date.now()}-${current.length}`, recipientId: 'custom', recipientName: '', recipientType: 'npc', rewardType: 'narrative', detail: '', playerText: '' }]);
  return <Modal title="Issue Bonus Objective" close={close}><div className="objective-heading"><span>OBJECTIVE OFFER REGISTER</span><p>Every active roster recipient is represented. Add Custom for a one-off offer or an additional trade.</p></div><label>Objective Title<input value={title} onChange={event => setTitle(event.target.value)}/></label><label>Summary<input value={summary} onChange={event => setSummary(event.target.value)}/></label><div className="trade-stack">{rows.map((row, index) => <article className={`trade-card ${row.enabled === false ? 'trade-disabled' : ''}`} key={row.id}><header><span>{row.recipientType === 'index' ? 'INDEX OFFER' : `OFFER ${index + 1}`}</span><strong>{row.recipientName || 'Custom recipient'}</strong>{row.recipientType !== 'index' && <label className="interest-toggle"><input type="checkbox" checked={row.enabled !== false} onChange={event => change(row.id, 'enabled', event.target.checked)}/><span>{row.enabled === false ? 'Not interested' : 'Interested'}</span></label>}</header>{row.recipientId === 'custom' && <label>Custom recipient<input value={row.recipientName} onChange={event => change(row.id, 'recipientName', event.target.value)}/></label>}{row.recipientType === 'index' ? <label>Trade Coin<select value={row.amount} onChange={event => change(row.id, 'amount', Number(event.target.value))}><option value={1}>1 TC</option><option value={2}>2 TC</option></select></label> : <label>Reward type<select value={row.rewardType} onChange={event => change(row.id, 'rewardType', event.target.value)}><option value="rp">RP</option><option value="reputation">Reputation</option><option value="battle-honour">Battle Honour</option><option value="asset">Asset</option><option value="narrative">Narrative</option></select></label>}<label>Trade value / detail<input value={row.detail} onChange={event => change(row.id, 'detail', event.target.value)}/></label><label>Player-facing offer<input value={row.playerText} onChange={event => change(row.id, 'playerText', event.target.value)}/></label>{row.recipientId === 'custom' && <button className="quiet-button" onClick={() => setRows(current => current.filter(entry => entry.id !== row.id))}>Remove offer</button>}</article>)}</div><div className="modal-actions"><button className="quiet-button" onClick={add}>+ Add custom offer</button><button onClick={() => save(title, summary, rows)}>Record objective</button></div></Modal>;
}
