import { useEffect, useMemo, useState } from 'react';
import { formatCampaignDate } from '../../market';
import type { CampaignControlState, CampaignDate, CampaignIdentity, CampaignPublication, CampaignSession, Cipher17State, EvidenceRecord, NpcRelationship } from '../../types';
import { campaignFetch } from '../../runtime';

const gmHeaders = { 'Content-Type': 'application/json' };
async function request<T>(url: string, options?: RequestInit, headers: HeadersInit = gmHeaders): Promise<T> {
  const response = await campaignFetch(url, { ...options, headers: { ...headers, ...(options?.headers ?? {}) } });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.error ?? 'The campaign API rejected this action.');
  return body as T;
}
const reportError = (report: (text: string) => void, error: unknown) => report(error instanceof Error ? error.message : 'The campaign action could not be completed.');

export const campaignLedgerCss = `.campaign-ledger{max-width:1260px}.campaign-ledger .ledger-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.campaign-ledger .ledger-panel{padding:20px;border:1px solid #526159;background:#14201d}.campaign-ledger .ledger-panel.wide{grid-column:1/-1}.campaign-ledger label{display:block;margin:10px 0}.campaign-ledger input,.campaign-ledger textarea,.campaign-ledger select{width:100%;margin-top:5px;padding:9px;color:#eee5d2;background:#0d1513;border:1px solid #6f765f}.campaign-ledger textarea{min-height:74px;resize:vertical}.campaign-ledger .item-row{display:flex;align-items:start;gap:12px;justify-content:space-between;flex-wrap:wrap;padding:12px 0;border-top:1px solid #45534d}.campaign-ledger .item-row p{margin:4px 0;color:#c9d1c6}.campaign-ledger .stat-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:16px 0}.campaign-ledger .stat-grid div{padding:12px;border:1px solid #45534d;background:#101a18}.campaign-ledger .stat-grid span{display:block;color:#9fb0a6;font-size:.78rem}.campaign-ledger .stat-grid strong{font-size:1.2rem}.campaign-ledger .warning{padding:10px;border-left:3px solid #d7a855;background:#302718;color:#f5ddaa}.campaign-ledger .cipher-marks{display:flex;gap:7px;margin:12px 0}.campaign-ledger .cipher-marks i{width:22px;height:22px;border:1px solid #7e8b76;border-radius:50%}.campaign-ledger .cipher-marks i.filled{background:#64d6d6;box-shadow:0 0 9px #2d8585}.campaign-ledger .gm-secret{color:#e5b867;font-size:.85rem}.briefings{max-width:900px}.briefing-card{margin:16px 0;padding:20px;border:1px solid #a98a54;background:#14201d}.briefing-card h2{margin-top:0}@media(max-width:760px){.campaign-ledger .ledger-grid{grid-template-columns:1fr}.campaign-ledger .stat-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}`;

function FormButton({ action, children }: { action: () => Promise<void>; children: React.ReactNode }) { const [busy, setBusy] = useState(false); return <button disabled={busy} onClick={() => { setBusy(true); void action().finally(() => setBusy(false)); }}>{busy ? 'Recording…' : children}</button>; }

export function CampaignLedger({ currentDate, report }: { currentDate: CampaignDate; report: (text: string) => void }) {
  const [control, setControl] = useState<CampaignControlState>(); const [title, setTitle] = useState(''); const [purpose, setPurpose] = useState(''); const [closeSummary, setCloseSummary] = useState(''); const [recap, setRecap] = useState('');
  const [publicationTitle, setPublicationTitle] = useState(''); const [publicationBody, setPublicationBody] = useState(''); const [publicationKind, setPublicationKind] = useState<CampaignPublication['kind']>('briefing');
  const [mandateTitle, setMandateTitle] = useState(''); const [mandateScope, setMandateScope] = useState(''); const [mandateObjectives, setMandateObjectives] = useState(''); const [route, setRoute] = useState(''); const [rosettePurpose, setRosettePurpose] = useState(''); const [rosetteConsequence, setRosetteConsequence] = useState('');
  const [contact, setContact] = useState(''); const [cipherPurpose, setCipherPurpose] = useState(''); const [category, setCategory] = useState<Cipher17State['uses'][number]['category']>('verify-record'); const [complication, setComplication] = useState('');
  const [npc, setNpc] = useState(''); const [relationshipState, setRelationshipState] = useState<NpcRelationship['state']>('open'); const [relationshipCause, setRelationshipCause] = useState(''); const [track, setTrack] = useState('track-uzazaban-command'); const [favour, setFavour] = useState(1); const [favourReason, setFavourReason] = useState('');
  const [evidenceTitle, setEvidenceTitle] = useState(''); const [knownClaim, setKnownClaim] = useState(''); const [gmTruth, setGmTruth] = useState(''); const [custodian, setCustodian] = useState('The Cell'); const [source, setSource] = useState('Session record'); const [transferEvidenceId, setTransferEvidenceId] = useState(''); const [transferCustodian, setTransferCustodian] = useState(''); const [transferReason, setTransferReason] = useState(''); const [mysteryTitle, setMysteryTitle] = useState(''); const [mysteryQuestion, setMysteryQuestion] = useState(''); const [mysteryTruth, setMysteryTruth] = useState('');
  const [debtTitle, setDebtTitle] = useState(''); const [debtor, setDebtor] = useState('The Cell'); const [creditor, setCreditor] = useState(''); const [hookTitle, setHookTitle] = useState(''); const [hookDetail, setHookDetail] = useState('');
  const load = async () => setControl(await request<CampaignControlState>('/campaign/control'));
  useEffect(() => { void load().catch(error => reportError(report, error)); }, []);
  const act = async (run: () => Promise<unknown>) => { try { await run(); await load(); } catch (error) { reportError(report, error); } };
  if (!control) return <main className="control campaign-ledger"><p>Loading campaign ledger…</p></main>;
  const active = control.sessions.find((entry) => entry.status === 'active'); const activeEvidence = control.evidence.filter((entry) => entry.status === 'active'); const activeMysteries = control.mysteries.filter((entry) => entry.status === 'open'); const npcs = control.directory.filter((entry) => entry.type === 'npc' && entry.active);
  return <main className="control campaign-ledger"><header className="control-header"><div><p className="eyebrow">GM-only · campaign command</p><h1>Active Campaign Ledger</h1></div><a className="display-link" href="#/">Return to Control</a></header><p className="form-error">Trusted-local GM tool. Publication is private by default; player projections never include GM truth, custody, or private authority records.</p>
    <section className="stat-grid"><div><span>Campaign date</span><strong>{formatCampaignDate(currentDate)}</strong></div><div><span>Session</span><strong>{active ? `#${active.number}` : 'None active'}</strong></div><div><span>Active evidence</span><strong>{activeEvidence.length}</strong></div><div><span>Open mysteries</span><strong>{activeMysteries.length}</strong></div></section>
    <div className="ledger-grid"><section className="ledger-panel"><p className="eyebrow">Daily record</p><h2>Session command</h2>{active ? <><div className="item-row"><div><strong>#{active.number} · {active.title}</strong><p>{active.purpose} · opened {formatCampaignDate(active.openedDate)}</p></div></div><label>Outcome summary<textarea value={closeSummary} onChange={event => setCloseSummary(event.target.value)} /></label><label>Draft player recap<textarea value={recap} onChange={event => setRecap(event.target.value)} /></label><FormButton action={() => act(() => request(`/campaign/sessions/${active.id}/close`, { method: 'POST', body: JSON.stringify({ outcomeSummary: closeSummary, aftermath: [], draftRecap: recap }) }))}>Close session and prepare aftermath</FormButton>{active.draftRecap && <FormButton action={() => act(() => request('/campaign/publications', { method: 'POST', body: JSON.stringify({ kind: 'session-recap', title: `${active.title} recap`, body: active.draftRecap, sourceType: 'session', sourceId: active.id }) }))}>Create recap publication draft</FormButton>}</> : <><label>Session title<input value={title} onChange={event => setTitle(event.target.value)} /></label><label>Purpose<textarea value={purpose} onChange={event => setPurpose(event.target.value)} /></label><FormButton action={() => act(async () => { await request('/campaign/sessions', { method: 'POST', body: JSON.stringify({ title, purpose }) }); setTitle(''); setPurpose(''); })}>Start campaign session</FormButton></>}</section>
      <section className="ledger-panel"><p className="eyebrow">Published projection</p><h2>Player briefings & recaps</h2><label>Publication type<select value={publicationKind} onChange={event => setPublicationKind(event.target.value as CampaignPublication['kind'])}>{['briefing','session-recap','objective','npc-profile','evidence-summary'].map((entry) => <option key={entry} value={entry}>{entry}</option>)}</select></label><label>Public title<input value={publicationTitle} onChange={event => setPublicationTitle(event.target.value)} /></label><label>Player-safe text<textarea value={publicationBody} onChange={event => setPublicationBody(event.target.value)} /></label><FormButton action={() => act(async () => { await request('/campaign/publications', { method: 'POST', body: JSON.stringify({ kind: publicationKind, title: publicationTitle, body: publicationBody, sourceType: active ? 'session' : 'campaign', sourceId: active?.id ?? 'campaign-ledger' }) }); setPublicationTitle(''); setPublicationBody(''); })}>Create publication draft</FormButton>{control.publications.length ? control.publications.map((entry) => <div className="item-row" key={entry.id}><div><strong>{entry.title}</strong><p>{entry.kind} · {entry.status}</p></div>{entry.status === 'draft' ? <FormButton action={() => act(() => request(`/campaign/publications/${entry.id}/status`, { method: 'POST', body: JSON.stringify({ status: 'published' }) }))}>Publish</FormButton> : entry.status === 'published' ? <FormButton action={() => act(() => request(`/campaign/publications/${entry.id}/status`, { method: 'POST', body: JSON.stringify({ status: 'withdrawn' }) }))}>Withdraw</FormButton> : null}</div>) : <p>No campaign material has been published.</p>}<a className="display-link" href="#/briefings" target="_blank">Open player briefings</a></section>
      <section className="ledger-panel"><p className="eyebrow">Sabine-sponsored authority</p><h2>Mandates & recognition</h2><p>{control.mandates.filter((entry) => entry.qualifying).length} / 3 qualifying missions toward collective Inquisition recognition.</p><label>Mandate title<input value={mandateTitle} onChange={event => setMandateTitle(event.target.value)} /></label><label>Specific scope<textarea value={mandateScope} onChange={event => setMandateScope(event.target.value)} /></label><label>Objectives<textarea value={mandateObjectives} onChange={event => setMandateObjectives(event.target.value)} /></label><label>Support route<input value={route} onChange={event => setRoute(event.target.value)} placeholder="Cover, record access, contact…" /></label><FormButton action={() => act(async () => { await request('/campaign/mandates', { method: 'POST', body: JSON.stringify({ title: mandateTitle, scope: mandateScope, objectives: mandateObjectives, supportRoute: route, sessionId: active?.id }) }); setMandateTitle(''); setMandateScope(''); setMandateObjectives(''); setRoute(''); })}>Record mandate</FormButton>{control.mandates.map((entry) => <div className="item-row" key={entry.id}><div><strong>{entry.title}</strong><p>{entry.status}{entry.result ? ` · ${entry.result}` : ''}</p></div>{entry.status === 'active' && <><FormButton action={() => act(() => request(`/campaign/mandates/${entry.id}/debrief`, { method: 'POST', body: JSON.stringify({ result: 'success', debrief: 'GM recorded successful debrief.' }) }))}>Debrief success</FormButton><FormButton action={() => act(() => request(`/campaign/mandates/${entry.id}/debrief`, { method: 'POST', body: JSON.stringify({ result: 'partial-success', debrief: 'GM recorded partial-success debrief.' }) }))}>Debrief partial</FormButton></>}</div>)}<label>Rosette invocation purpose<textarea value={rosettePurpose} onChange={event => setRosettePurpose(event.target.value)} /></label><label>Sealed consequence/reviewer note<textarea value={rosetteConsequence} onChange={event => setRosetteConsequence(event.target.value)} /></label><FormButton action={() => act(() => request('/campaign/rosette-invocations', { method: 'POST', body: JSON.stringify({ purpose: rosettePurpose, consequence: rosetteConsequence, sessionId: active?.id }) }))}>Record rosette invocation</FormButton><p className="gm-secret">{control.rosetteInvocations.length} sealed Sigillary audit entr{control.rosetteInvocations.length === 1 ? 'y' : 'ies'}.</p></section>
      <section className="ledger-panel"><p className="eyebrow">Shared limited network</p><h2>Cipher-17</h2><div className="cipher-marks" aria-label={`${control.cipher17.availableMarks} Cipher-17 marks available`}>{Array.from({ length: control.cipher17.maximumMarks }, (_, index) => <i className={index < control.cipher17.availableMarks ? 'filled' : ''} key={index}/>)}</div><p>{control.cipher17.availableMarks} marks · Exposure {control.cipher17.exposure}/3 · {control.cipher17.status}</p>{control.cipher17.status === 'complication-required' && <><label>Required Exposure complication<textarea value={complication} onChange={event => setComplication(event.target.value)} /></label><FormButton action={() => act(() => request('/campaign/cipher/complication', { method: 'POST', body: JSON.stringify({ detail: complication }) }))}>Record complication</FormButton></>}{active && control.cipher17.status === 'available' && <><label>Named contact<input value={contact} onChange={event => setContact(event.target.value)} /></label><label>Canonical use<select value={category} onChange={event => setCategory(event.target.value as typeof category)}><option value="verify-record">Verify or compare a record</option><option value="introduction-or-passage">Introduction, meeting, or passage</option><option value="modest-item-or-disguise">Modest item, disguise, or local map</option><option value="extraction-message-or-warning">Extraction, message, or warning</option></select></label><label>Purpose<textarea value={cipherPurpose} onChange={event => setCipherPurpose(event.target.value)} /></label><FormButton action={() => act(() => request('/campaign/cipher/use', { method: 'POST', body: JSON.stringify({ sessionId: active.id, contact, category, purpose: cipherPurpose }) }))}>Spend Cipher mark</FormButton></>}</section>
      <section className="ledger-panel wide"><p className="eyebrow">People and institutional credit</p><h2>Relationships, Influence & Favour</h2><div className="ledger-grid"><div><label>Canonical NPC<select value={npc} onChange={event => setNpc(event.target.value)}><option value="">Choose NPC</option>{npcs.map((entry) => <option key={entry.id} value={entry.id}>{entry.name}</option>)}</select></label><label>Relationship state<select value={relationshipState} onChange={event => setRelationshipState(event.target.value as NpcRelationship['state'])}>{['open','wary','owed','indebted','hostile'].map((entry) => <option key={entry}>{entry}</option>)}</select></label><label>Durable cause<textarea value={relationshipCause} onChange={event => setRelationshipCause(event.target.value)} /></label><FormButton action={() => act(() => request('/campaign/relationships', { method: 'POST', body: JSON.stringify({ directoryId: npc, state: relationshipState, protected: false, exposed: false, cause: relationshipCause, sessionId: active?.id }) }))}>Record relationship</FormButton></div><div><label>Favour amount<input type="number" value={favour} onChange={event => setFavour(Number(event.target.value))}/></label><label>Reason<textarea value={favourReason} onChange={event => setFavourReason(event.target.value)} /></label><FormButton action={() => act(() => request(`/campaign/influence/${track}`, { method: 'POST', body: JSON.stringify({ kind: 'favour', amount: favour, reason: favourReason, sourceType: 'session', sourceId: active?.id }) }))}>Record Favour</FormButton>{control.influenceTracks.map((entry) => <p key={entry.id}><strong>{entry.subjectName}</strong> · Influence {entry.value >= 0 ? '+' : ''}{entry.value} · Favour {entry.favour}{entry.configuredThresholds ? ' · configured thresholds active' : ''}</p>)}</div></div></section>
      <section className="ledger-panel wide"><p className="eyebrow">Truth, custody, and multiple routes</p><h2>Evidence & mysteries</h2><div className="ledger-grid"><div><label>Evidence title<input value={evidenceTitle} onChange={event => setEvidenceTitle(event.target.value)} /></label><label>Player-known claim<textarea value={knownClaim} onChange={event => setKnownClaim(event.target.value)} /></label><label>GM truth<textarea value={gmTruth} onChange={event => setGmTruth(event.target.value)} /></label><label>Current custodian<input value={custodian} onChange={event => setCustodian(event.target.value)} /></label><FormButton action={() => act(async () => { await request('/campaign/evidence', { method: 'POST', body: JSON.stringify({ title: evidenceTitle, knownClaim, gmTruth, source, reliability: 'credible', form: 'original', currentCustodian: custodian, seekers: [], compromised: false, exposed: false, linkedDirectoryIds: [], linkedSessionIds: active ? [active.id] : [], linkedOperationIds: [], unresolvedQuestions: [], status: 'active' }) }); setEvidenceTitle(''); setKnownClaim(''); setGmTruth(''); })}>Record evidence</FormButton>{activeEvidence.map((entry) => <p key={entry.id}><strong>{entry.title}</strong> · custody: {entry.currentCustodian} <span className="gm-secret">GM truth retained</span></p>)}<label>Transfer evidence<select value={transferEvidenceId} onChange={event => setTransferEvidenceId(event.target.value)}><option value="">Choose evidence</option>{activeEvidence.map((entry) => <option key={entry.id} value={entry.id}>{entry.title}</option>)}</select></label><label>New custodian<input value={transferCustodian} onChange={event => setTransferCustodian(event.target.value)} /></label><label>Transfer reason<textarea value={transferReason} onChange={event => setTransferReason(event.target.value)} /></label><FormButton action={() => act(() => request(`/campaign/evidence/${transferEvidenceId}/custody`, { method: 'POST', body: JSON.stringify({ custodian: transferCustodian, reason: transferReason, sourceType: 'session', sourceId: active?.id }) }))}>Transfer custody</FormButton></div><div><label>Mystery title<input value={mysteryTitle} onChange={event => setMysteryTitle(event.target.value)} /></label><label>Question<textarea value={mysteryQuestion} onChange={event => setMysteryQuestion(event.target.value)} /></label><label>GM truth<textarea value={mysteryTruth} onChange={event => setMysteryTruth(event.target.value)} /></label><FormButton action={() => act(() => request('/campaign/mysteries', { method: 'POST', body: JSON.stringify({ title: mysteryTitle, question: mysteryQuestion, gmTruth: mysteryTruth, essential: true, evidenceIds: activeEvidence.map((entry) => entry.id), currentLeads: [], status: 'open' }) }))}>Record mystery</FormButton>{activeMysteries.map((entry) => <p key={entry.id}><strong>{entry.title}</strong> · {entry.evidenceIds.length} evidence route{entry.evidenceIds.length === 1 ? '' : 's'}</p>)}</div></div></section>
      <section className="ledger-panel"><h2>Debts</h2><label>Debt title<input value={debtTitle} onChange={event => setDebtTitle(event.target.value)} /></label><label>Creditor<input value={creditor} onChange={event => setCreditor(event.target.value)} /></label><FormButton action={() => act(() => request('/campaign/debts', { method: 'POST', body: JSON.stringify({ title: debtTitle, debtor, creditor, detail: debtTitle, status: 'open' }) }))}>Record debt</FormButton>{control.debts.filter((entry) => entry.status === 'open').map((entry) => <p key={entry.id}><strong>{entry.title}</strong> · {entry.debtor} owes {entry.creditor}</p>)}</section>
      <section className="ledger-panel"><h2>Next hooks</h2><label>Hook title<input value={hookTitle} onChange={event => setHookTitle(event.target.value)} /></label><label>Detail<textarea value={hookDetail} onChange={event => setHookDetail(event.target.value)} /></label><FormButton action={() => act(() => request('/campaign/hooks', { method: 'POST', body: JSON.stringify({ title: hookTitle, detail: hookDetail, status: 'open', priority: 'normal' }) }))}>Record hook</FormButton>{control.hooks.filter((entry) => entry.status === 'open').map((entry) => <p key={entry.id}><strong>{entry.title}</strong> · {entry.detail}</p>)}</section>
    </div></main>;
}

export function PlayerBriefings({ report }: { report: (text: string) => void }) {
  const [publications, setPublications] = useState<CampaignPublication[]>([]); const [identities, setIdentities] = useState<CampaignIdentity[]>([]); const [identityId, setIdentityId] = useState(''); const [acknowledged, setAcknowledged] = useState<string[]>([]);
  const load = async () => { const playerHeaders = { 'X-Trusted-Local-Role': 'player' }; const [projection, people] = await Promise.all([request<{ control: Pick<CampaignControlState, 'publications'> }>('/campaign/projection?role=player', undefined, playerHeaders), request<CampaignIdentity[]>('/campaign/identities', undefined, playerHeaders)]); setPublications(projection.control.publications); setIdentities(people.filter((entry) => entry.role === 'player')); };
  useEffect(() => { void load().catch(error => reportError(report, error)); }, []);
  const acknowledge = async (publicationId: string) => { try { await request(`/campaign/publications/${publicationId}/acknowledge`, { method: 'POST', body: JSON.stringify({ idempotencyKey: `${identityId}:${publicationId}` }) }, { 'Content-Type': 'application/json', 'X-Trusted-Local-Role': 'player', 'X-Campaign-Identity': identityId }); setAcknowledged((value) => [...value, publicationId]); } catch (error) { reportError(report, error); } };
  return <main className="display briefings"><header className="gallery-header"><a className="display-link player-atlas-return" href="#/atlas">← Back to Tavrellis Atlas</a><p className="eyebrow">Published campaign record</p><h1>Cell briefings</h1></header><p>Only material explicitly published by the GM appears here.</p>{identities.length ? <label>Local player identity<select value={identityId} onChange={event => setIdentityId(event.target.value)}><option value="">Choose identity</option>{identities.map((entry) => <option key={entry.id} value={entry.id}>{entry.name}</option>)}</select></label> : <p>No local player identity is configured. Published records remain readable.</p>}{publications.length ? publications.map((entry) => <article className="briefing-card" key={entry.id}><p className="eyebrow">{entry.kind}</p><h2>{entry.title}</h2><p>{entry.body}</p>{identityId && <button disabled={acknowledged.includes(entry.id)} onClick={() => void acknowledge(entry.id)}>{acknowledged.includes(entry.id) ? 'Acknowledged' : 'Acknowledge briefing'}</button>}</article>) : <p>No campaign briefings are currently published.</p>}</main>;
}
