import { useEffect, useState } from 'react';
import type { CampaignControlState, CampaignIdentity, ClaimedAssetDisposition, DiscoveryInstance, RpTransactionKind } from '../../types';
import { campaignFetch } from '../../runtime';

const gmHeaders = { 'Content-Type': 'application/json' };
async function request<T>(url: string, options?: RequestInit, headers: HeadersInit = gmHeaders): Promise<T> { const response = await campaignFetch(url, { ...options, headers: { ...headers, ...(options?.headers ?? {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error ?? 'The campaign service rejected this request.'); return body as T; }
const failure = (report: (message: string) => void, error: unknown) => report(error instanceof Error ? error.message : 'The economy action could not be completed.');

export function EconomyPage({ report }: { report: (message: string) => void }) {
  const [control, setControl] = useState<CampaignControlState>(); const [balance, setBalance] = useState(0); const [identities, setIdentities] = useState<CampaignIdentity[]>([]);
  const [participants, setParticipants] = useState(3); const [result, setResult] = useState<'win' | 'loss'>('win'); const [reason, setReason] = useState('');
  const [manualAmount, setManualAmount] = useState(1); const [manualKind, setManualKind] = useState<Extract<RpTransactionKind, 'liability-award' | 'exceptional-discovery' | 'exceptional-outcome' | 'correction'>>('liability-award'); const [manualReason, setManualReason] = useState('');
  const [assetTitle, setAssetTitle] = useState(''); const [assetClass, setAssetClass] = useState<'minor' | 'major' | 'exceptional'>('minor'); const [assetRecipient, setAssetRecipient] = useState('faction-uzazaban-command'); const [assetReason, setAssetReason] = useState(''); const [assetKind, setAssetKind] = useState<ClaimedAssetDisposition>('donation-standard');
  const [templateId, setTemplateId] = useState(''); const [ownerMode, setOwnerMode] = useState<'personal' | 'shared'>('shared'); const [ownerId, setOwnerId] = useState('');
  const load = async () => { const [economy, all, gmControl] = await Promise.all([request<CampaignControlState['economy'] & { balance: number }>('/campaign/economy'), request<CampaignIdentity[]>('/campaign/identities'), request<CampaignControlState>('/campaign/control')]); setControl({ ...gmControl, economy }); setBalance(economy.balance); setIdentities(all); if (!templateId) setTemplateId(economy.discoveryTemplates[0]?.id ?? ''); };
  useEffect(() => { void load().catch(error => failure(report, error)); }, []);
  const call = async (url: string, body: unknown) => { try { await request(url, { method: 'POST', body: JSON.stringify(body) }); await load(); } catch (error) { failure(report, error); } };
  const economy = control?.economy;
  const activeAssets = economy?.claimedAssets.filter((asset) => ['recovered', 'investigated', 'disputed'].includes(asset.status)) ?? [];
  return <main className="control economy-page"><header className="control-header"><div><p className="eyebrow">GM-only · canonical shared reserve</p><h1>Campaign Economy</h1></div><a className="display-link" href="#/">Return to Control</a></header>
    <section className="economy-summary"><article><span>Shared RP reserve</span><strong>{balance} RP</strong></article><article><span>Pending requisitions</span><strong>{economy?.requisitions.filter((row) => row.status === 'proposed' || row.status === 'approved').length ?? 0}</strong></article><article><span>Unresolved assets</span><strong>{activeAssets.length}</strong></article><article><span>Active discoveries</span><strong>{economy?.discoveries.filter((row) => row.status === 'unused').length ?? 0}</strong></article></section>
    <section className="economy-grid"><article><h2>Standard battle award</h2><label>Participating players<input type="number" min="1" value={participants} onChange={(event) => setParticipants(Number(event.target.value))}/></label><label>Result<select value={result} onChange={(event) => setResult(event.target.value as 'win' | 'loss')}><option value="win">Win · 1 RP each</option><option value="loss">Loss · floor(players ÷ 2) RP</option></select></label><label>Reason<input value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Operation or battle reference"/></label><button onClick={() => void call('/campaign/economy/battle-award', { participants, result, reason })}>Confirm standard award</button>
      <h3>Exceptional or liability award</h3><label>RP amount<input type="number" value={manualAmount} onChange={(event) => setManualAmount(Number(event.target.value))}/></label><label>Category<select value={manualKind} onChange={(event) => setManualKind(event.target.value as typeof manualKind)}><option value="liability-award">Liability accepted · 1 RP</option><option value="exceptional-discovery">Exceptional discovery · 2 RP</option><option value="exceptional-outcome">Exceptional outcome · 2 RP</option><option value="correction">Reasoned correction</option></select></label><label>Reason<input value={manualReason} onChange={(event) => setManualReason(event.target.value)}/></label><button onClick={() => void call('/campaign/economy/award', { amount: manualAmount, kind: manualKind, reason: manualReason })}>Record award</button></article>
      <article><h2>Requisitions</h2>{economy?.requisitions.map((row) => <div className="economy-row" key={row.id}><strong>{row.title}</strong><span>{row.cost} RP · {row.status}</span>{row.status === 'proposed' && <button onClick={() => void call(`/campaign/economy/requisitions/${row.id}`, { status: 'approved' })}>Approve</button>}{row.status === 'approved' && <button onClick={() => void call(`/campaign/economy/requisitions/${row.id}`, { status: 'spent' })}>Spend RP</button>}</div>) ?? <p>No requisitions recorded.</p>}<RequisitionForm call={call}/></article>
      <article><h2>Claimed Assets</h2>{activeAssets.map((asset) => <div className="economy-row" key={asset.id}><strong>{asset.title}</strong><span>{asset.assetClass} · {asset.status}</span><button onClick={() => void call(`/campaign/economy/assets/${asset.id}/dispose`, { kind: assetKind, recipientDirectoryId: assetRecipient || undefined, reason: assetReason, negotiatedRp: assetKind === 'anonymous-sale' ? 1 : undefined })}>Confirm disposition</button></div>)}<h3>Disposition controls</h3><label>Disposition<select value={assetKind} onChange={(event) => setAssetKind(event.target.value as ClaimedAssetDisposition)}>{['donation-standard','donation-major','exchange-ordinary','exchange-generous','anonymous-sale','retain','conceal','rival-transfer'].map((kind) => <option key={kind}>{kind}</option>)}</select></label><label>Recipient<select value={assetRecipient} onChange={(event) => setAssetRecipient(event.target.value)}><option value="">No recipient</option>{control?.directory.filter((entry) => entry.type === 'faction' || entry.type === 'institution').map((entry) => <option key={entry.id} value={entry.id}>{entry.name}</option>)}</select></label><label>Reason<input value={assetReason} onChange={(event) => setAssetReason(event.target.value)}/></label><h3>Record recovered asset</h3><label>Title<input value={assetTitle} onChange={(event) => setAssetTitle(event.target.value)}/></label><label>Class<select value={assetClass} onChange={(event) => setAssetClass(event.target.value as typeof assetClass)}><option value="minor">Minor</option><option value="major">Major</option><option value="exceptional">Exceptional</option></select></label><button onClick={() => void call('/campaign/economy/assets', { title: assetTitle, assetClass, targetSource: 'GM-recorded source', claimant: 'Unknown claimant', provenance: 'Pending investigation', recovery: 'Recovered', extraction: 'Recorded by GM', tacticalRisk: 'GM review required', currentCustodian: 'The Cell', condition: 'Intact', linkedEvidenceIds: [], publicDescription: assetTitle })}>Record Claimed Asset</button></article>
      <article><h2>Discovery chains</h2>{economy?.discoveries.map((row) => <div className="economy-row" key={row.id}><strong>{row.templateTitle}</strong><span>{row.ownerMode} · {row.status}</span>{row.status === 'unused' && <button onClick={() => void call(`/campaign/economy/discoveries/${row.id}`, { status: 'spent', reason: 'GM recorded use.' })}>Mark spent</button>}</div>) ?? <p>No discoveries issued.</p>}<label>Canonical template<select value={templateId} onChange={(event) => setTemplateId(event.target.value)}>{economy?.discoveryTemplates.map((row) => <option key={row.id} value={row.id}>{row.title}{row.honourGate ? ' · Honour frozen' : ''}</option>)}</select></label><label>Ownership<select value={ownerMode} onChange={(event) => setOwnerMode(event.target.value as typeof ownerMode)}><option value="shared">Shared</option><option value="personal">Personal</option></select></label>{ownerMode === 'personal' && <label>Player owner<select value={ownerId} onChange={(event) => setOwnerId(event.target.value)}><option value="">Choose player</option>{identities.filter((entry) => entry.role === 'player').map((entry) => <option key={entry.id} value={entry.id}>{entry.name}</option>)}</select></label>}<button onClick={() => void call('/campaign/economy/discoveries', { templateId, ownerMode, ownerIdentityId: ownerId || undefined })}>Issue discovery</button></article>
    </section><section className="rp-history"><h2>RP history</h2>{economy?.rpTransactions.slice().reverse().map((row) => <article key={row.id}><strong>{row.amount > 0 ? '+' : ''}{row.amount} RP</strong><span>{row.kind} · {row.reason}</span></article>)}</section></main>;
}

function RequisitionForm({ call }: { call: (url: string, body: unknown) => Promise<void> }) { const [title, setTitle] = useState(''); const [kind, setKind] = useState<'rank-advancement' | 'major-reinforcement' | 'certified'>('certified'); const [cost, setCost] = useState(1); const [source, setSource] = useState(''); const [target, setTarget] = useState(''); const [effect, setEffect] = useState(''); return <div className="economy-form"><h3>Propose requisition</h3><label>Title<input value={title} onChange={(event) => setTitle(event.target.value)}/></label><label>Kind<select value={kind} onChange={(event) => { const value = event.target.value as typeof kind; setKind(value); if (value === 'rank-advancement') setCost(1); if (value === 'major-reinforcement') setCost(3); }}><option value="certified">Certified requisition</option><option value="rank-advancement">Rank advancement · 1 RP</option><option value="major-reinforcement">Major Reinforcement · 3 RP</option></select></label><label>RP cost<input type="number" value={cost} onChange={(event) => setCost(Number(event.target.value))}/></label><label>Source<input value={source} onChange={(event) => setSource(event.target.value)}/></label><label>Target<input value={target} onChange={(event) => setTarget(event.target.value)}/></label><label>Exact effect<input value={effect} onChange={(event) => setEffect(event.target.value)}/></label><button onClick={() => void call('/campaign/economy/requisitions', { title, kind, cost, source, target, effect })}>Propose requisition</button></div>; }

type PlayerResourcesData = {
  balance: number;
  assets: { id: string; title: string; status: string; publicDescription: string; condition: string }[];
  discoveries: { id: string; templateTitle: string; status: string; ownerMode: string; publicDescription: string }[];
};

const playerResourcesCss = `.resources-page{max-width:1080px;margin:auto;padding:24px}.resources-page .player-atlas-return{display:inline-flex;margin:0 0 12px}.resource-summary{display:grid;grid-template-columns:minmax(170px,.6fr) 1fr;gap:14px;margin:18px 0}.resource-summary article,.resource-section{border:1px solid #496056;background:#101c18;padding:16px}.resource-summary strong{display:block;font:700 2rem Georgia,serif;color:#f1d8a2;margin-top:4px}.resource-section{margin:16px 0}.resource-section h2{margin:0 0 8px}.resource-section > p{margin:0;color:#b8c5bc}.resource-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.resource-list .briefing-card{margin:0}.resource-eyebrow{font:700 .7rem Arial,sans-serif;letter-spacing:.1em;text-transform:uppercase;color:#75d8dc}@media(max-width:680px){.resources-page{padding:14px}.resource-summary{grid-template-columns:1fr}}`;

export function PlayerResources({ report }: { report: (message: string) => void }) {
  const [identityId, setIdentityId] = useState('');
  const [people, setPeople] = useState<CampaignIdentity[]>([]);
  const [resources, setResources] = useState<PlayerResourcesData>();
  const load = async (id = identityId) => {
    const headers = { 'X-Trusted-Local-Role': 'player', ...(id ? { 'X-Campaign-Identity': id } : {}) };
    const [rows, economy] = await Promise.all([
      request<CampaignIdentity[]>('/campaign/identities', undefined, headers),
      request<PlayerResourcesData>('/campaign/economy', undefined, headers),
    ]);
    setPeople(rows);
    setResources(economy);
  };
  useEffect(() => { void load().catch(error => failure(report, error)); }, []);
  const sharedDiscoveries = resources?.discoveries?.filter(entry => entry.ownerMode === 'shared') ?? [];
  const personalDiscoveries = resources?.discoveries?.filter(entry => entry.ownerMode !== 'shared') ?? [];
  return <main className="display resources-page"><style>{playerResourcesCss}</style>
    <header className="gallery-header"><a className="display-link player-atlas-return" href="#/atlas">← Back to Tavrellis Atlas</a><p className="eyebrow">Published campaign resources</p><h1>Cell resources</h1></header>
    <label>Local player identity<select value={identityId} onChange={(event) => { setIdentityId(event.target.value); void load(event.target.value).catch(error => failure(report, error)); }}><option value="">Shared Cell view</option>{people.map((entry) => <option key={entry.id} value={entry.id}>{entry.name}</option>)}</select></label>
    <section className="resource-summary" aria-label="Party resources"><article><span className="resource-eyebrow">Party resource pool</span><strong>{resources?.balance ?? 0} RP</strong><span>Shared Requisition Points</span></article><article><span className="resource-eyebrow">Shared discoveries</span><h2>{sharedDiscoveries.length ? `${sharedDiscoveries.length} available to the Cell` : 'No shared discoveries yet'}</h2><p>Shared discoveries and their published use limitations are available to the whole party.</p></article></section>
    <section className="resource-section"><p className="resource-eyebrow">Bonus objectives</p><h2>Bonus Objective credit</h2><p>Available Gilded Index objectives and their Trade Coin values appear at <a href="#/exchange">Miren’s counter</a>, where eligible objectives can be redeemed once.</p></section>
    <section className="resource-section"><p className="resource-eyebrow">Mission assets</p><h2>Approved mission assets</h2>{resources?.assets?.length ? <div className="resource-list">{resources.assets.map((asset) => <article className="briefing-card" key={asset.id}><h3>{asset.title}</h3><p>{asset.publicDescription}</p><span>{asset.status} · {asset.condition}</span></article>)}</div> : <p>No approved mission assets are currently visible.</p>}</section>
    <section className="resource-section"><p className="resource-eyebrow">Discoveries</p><h2>Shared and personal discoveries</h2>{resources?.discoveries?.length ? <div className="resource-list">{[...sharedDiscoveries, ...personalDiscoveries].map((entry) => <article className="briefing-card" key={entry.id}><h3>{entry.templateTitle}</h3><p>{entry.publicDescription}</p><span>{entry.ownerMode} · {entry.status}</span></article>)}</div> : <p>No discoveries are currently visible.</p>}</section>
  </main>;
}
