import { useEffect, useState } from 'react';
import { hostedRequest } from '../player/AuthGateway';
import { campaignFetch, getCampaignRuntime } from '../../runtime';

type Access = { accounts: Array<{ id: string; identityId: string; email: string; active: boolean; createdAt: string; updatedAt: string }>; sessions: Array<{ id: string; accountId?: string; kind: string; expiresAt: string; lastSeenAt: string }>; };
export function GmAccess({ report }: { report: (message: string) => void }) {
  if (getCampaignRuntime().mode === 'preview') return <main className="control campaign-management"><header className="control-header"><div><p className="eyebrow">Local preview boundary</p><h1>Campaign role access</h1></div><a className="display-link" href="#/">Return to Control</a></header><section className="source-search"><p>Assign preview campaign roles from the Tavern account controls. Hosted invitations, passwords, display links, and session revocation are intentionally unavailable until the site has a real authenticated backend.</p></section></main>;
  const [access, setAccess] = useState<Access>({ accounts: [], sessions: [] }); const [identityId, setIdentityId] = useState(''); const [email, setEmail] = useState(''); const [displayLink, setDisplayLink] = useState('');
  const load = () => campaignFetch('/auth/access').then(async response => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? 'Could not load account access.'); setAccess(payload); }).catch(error => report(error.message));
  useEffect(() => { void load(); }, []);
  const invite = async () => { const response = await hostedRequest('/api/auth/invite', { identityId, email }); const body = await response.json(); if (!response.ok) return report(body.error ?? 'Could not issue invitation.'); setEmail(''); void load(); };
  const display = async () => { const response = await hostedRequest('/api/auth/display', {}); const body = await response.json(); if (!response.ok) return report(body.error ?? 'Could not create display session.'); setDisplayLink(`${location.origin}/display-session?token=${encodeURIComponent(body.token)}`); void load(); };
  const revoke = async (id: string) => { const response = await hostedRequest(`/api/auth/sessions/${id}/revoke`, {}); const body = await response.json(); if (!response.ok) return report(body.error ?? 'Could not revoke session.'); void load(); };
  return <main className="control campaign-management"><header className="control-header"><div><p className="eyebrow">GM-only · hosted access</p><h1>Account & Display Access</h1></div><a className="display-link" href="#/">Return to Control</a></header><section className="campaign-grid"><article><h2>Invite player</h2><p>Choose an existing player identity; invitations expire after seven days.</p><label>Campaign identity<input value={identityId} onChange={event => setIdentityId(event.target.value)} placeholder="Player identity ID"/></label><label>Email<input type="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="player@example.com"/></label><button onClick={() => void invite()}>Issue invitation</button></article><article><h2>Table display</h2><p>Create a revocable, read-only 12-hour display session.</p><button onClick={() => void display()}>Launch display session</button>{displayLink && <label>Copy display link<input readOnly value={displayLink}/></label>}</article></section><section className="source-search"><h2>Accounts</h2>{access.accounts.length ? access.accounts.map(account => <article key={account.id}><strong>{account.email}</strong><span>{account.identityId} · {account.active ? 'active' : 'disabled'} · updated {new Date(account.updatedAt).toLocaleString()}</span></article>) : <p>No hosted accounts have been activated.</p>}<h2>Active sessions</h2>{access.sessions.map(session => <article key={session.id}><strong>{session.kind} session</strong><span>Expires {new Date(session.expiresAt).toLocaleString()}</span><button onClick={() => void revoke(session.id)}>Revoke</button></article>)}</section></main>;
}
