import React, { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import AtlasApp from './src/features/atlas/AtlasApp.tsx';
import atlasCss from './src/features/atlas/atlas.css';
import { accounts, getAccount, getAuthEventName } from '../preview/auth.mjs';

const scopeCss = source => source.replace(/:root\b/g, '.hybrid-campaign-shell').replace(/(^|[,{])\s*body\b/gm, '$1 .hybrid-campaign-shell');
const embeddedCss = `${scopeCss(atlasCss)}
  .hybrid-campaign-shell{min-height:100%;background:#0c1412;color:#eee5d2}.hybrid-return{position:sticky;z-index:20;top:0;display:flex;align-items:center;justify-content:space-between;gap:12px;padding:10px 18px;border-bottom:1px solid #6d785e;background:rgba(10,18,16,.96)}.hybrid-return a{color:#f2dfb0;text-decoration:none}.hybrid-return strong{font:700 .72rem Arial,sans-serif;letter-spacing:.12em;text-transform:uppercase;color:#71dbe1}.hybrid-hub{min-height:calc(100dvh - 45px);max-width:760px;margin:0 auto;padding:clamp(28px,5vw,68px) 22px}.hybrid-hub h1{margin:8px 0 16px;color:#f1d8a2;font:clamp(2rem,5vw,4.2rem) Georgia,serif}.hybrid-hub p{max-width:680px;color:#c6d2ca;line-height:1.6}.hybrid-onboarding{max-width:620px;padding:24px;border:1px solid #687c70;background:#13201c}.hybrid-onboarding label{display:grid;gap:6px;margin:14px 0}.hybrid-onboarding input,.hybrid-onboarding select{width:100%;min-height:42px}.hybrid-onboarding button{margin-top:8px}.hybrid-error{color:#ffb9a9}@media(max-width:640px){.hybrid-return{padding:9px 12px}.hybrid-return strong{display:none}}`;

const savedAccount = () => { const active = getAccount(); return accounts?.find(active.username) ?? null; };
const accountKeyFor = account => account?.testFixtureId ? `preview-test:${account.testFixtureId}` : `preview-account:${account?.id}`;
const readJson = async response => { const raw = await response.text(); if (!raw.trim()) throw new Error('The campaign preview returned an empty response. Reload and try again.'); try { return JSON.parse(raw); } catch { throw new Error('The campaign preview returned an invalid response. Reload and try again.'); } };
const request = async (path, accountKey, init = {}) => { const response = await fetch(`/hybrid-campaign/api${path}`, { ...init, headers: { Accept: 'application/json', 'X-Preview-Campaign-Role': 'player', 'X-Preview-Campaign-Account': accountKey, ...(init.headers || {}) } }); const body = await readJson(response); if (!response.ok) throw new Error(body.error || 'The local campaign service is unavailable.'); return body; };

function PlayerOnboarding({ account, onFinished }) {
  const [factions, setFactions] = useState([]); const [characterName, setCharacterName] = useState(''); const [recipientId, setRecipientId] = useState(''); const [supportingFactionName, setSupportingFactionName] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const accountKey = accountKeyFor(account);
  useEffect(() => { let active = true; void request('/preview/onboarding-options', accountKey).then(body => { if (!active) return; setFactions(body.factions || []); setRecipientId(body.factions?.[0]?.id || ''); }).catch(problem => { if (active) setError(problem.message); }); return () => { active = false; }; }, [accountKey]);
  const submit = async event => { event.preventDefault(); setError(''); setSaving(true); try { const body = await request('/preview/onboarding', accountKey, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ characterName, supportingFactionRecipientId: recipientId, supportingFactionName }) }); accounts.assignCampaignIdentity(account.id, body.identity.id); window.dispatchEvent(new Event(getAuthEventName())); onFinished(); window.location.hash = '#/atlas'; } catch (problem) { setError(problem instanceof Error ? problem.message : 'The player profile could not be created.'); } finally { setSaving(false); } };
  return <main className="hybrid-hub"><header><p className="eyebrow">Player profile setup</p><h1>Enter the Tavrellis campaign</h1><p>This local preview links one character to this Tavern account. The choice only controls the player-facing command deck.</p></header><form className="hybrid-onboarding" onSubmit={submit}><label>Character name<input required maxLength="80" value={characterName} onChange={event => setCharacterName(event.target.value)} /></label><label>Supporting faction<select required value={recipientId} onChange={event => setRecipientId(event.target.value)}>{factions.map(faction => <option key={faction.id} value={faction.id}>{faction.name}</option>)}</select></label><label>Supporting faction or warband name<input required maxLength="120" value={supportingFactionName} onChange={event => setSupportingFactionName(event.target.value)} placeholder="Your named support route" /></label>{error && <p className="hybrid-error" role="alert">{error}</p>}<button disabled={saving || !factions.length}>{saving ? 'Creating profile…' : 'Create campaign profile'}</button></form></main>;
}

export default function HybridCampaign() {
  const [version, setVersion] = useState(0); const [profileResolved, setProfileResolved] = useState(false); const account = useMemo(() => savedAccount(), [version]); const accountKey = accountKeyFor(account); const player = account?.campaignRole === 'player';
  useEffect(() => { const refresh = () => setVersion(value => value + 1); window.addEventListener(getAuthEventName(), refresh); return () => window.removeEventListener(getAuthEventName(), refresh); }, []);
  useEffect(() => accounts?.subscribe(() => setVersion(value => value + 1)), []);
  useEffect(() => { let active = true; setProfileResolved(!player || !!account?.campaignIdentityId); if (!player || account?.campaignIdentityId || !accountKey) return () => { active = false; }; void request('/preview/profile', accountKey).then(body => { if (!active) return; if (body.profile?.identityId) { accounts.assignCampaignIdentity(account.id, body.profile.identityId); window.dispatchEvent(new Event(getAuthEventName())); } setProfileResolved(true); }).catch(() => { if (active) setProfileResolved(true); }); return () => { active = false; }; }, [account?.id, account?.campaignIdentityId, accountKey, player]);
  const returnToTavern = () => { window.location.hash = ''; };
  return <section className="hybrid-campaign-shell"><style>{embeddedCss}</style><nav className="hybrid-return" aria-label="Campaign navigation"><Link to="/projects" onClick={returnToTavern}>← Return to the Tavern</Link><strong>Senseweeks’s Hybrid Campaign Experiment</strong></nav>{!player ? <main className="hybrid-hub"><p className="eyebrow">Campaign access</p><h1>Player clearance required</h1><p>Choose a saved account assigned the Hybrid Campaign player role to open the Tavrellis command deck.</p></main> : !profileResolved ? <main className="hybrid-hub"><p>Synchronising the local player profile…</p></main> : !account?.campaignIdentityId ? <PlayerOnboarding account={account} onFinished={() => setVersion(value => value + 1)} /> : <AtlasApp key={`${account.id}:${account.campaignIdentityId}`} accountKey={accountKey}/>}</section>;
}
